---
web:
  port: ${CUSTOM_WEB_PORT}
storage:
  type: postgres
  path: postgres://${INIT_POSTGRES_USER}:${INIT_POSTGRES_PASS}@${INIT_POSTGRES_HOST}:5432/${INIT_POSTGRES_DBNAME}?sslmode=disable
  caching: true
metrics: false
debug: false
ui:
  title: Status | Gatus
  header: Status
alerting:
  pushover:
    application-token: ${CUSTOM_PUSHOVER_APP_TOKEN}
    user-key: ${CUSTOM_PUSHOVER_USER_KEY}
    default-alert:
      description: health-check failed
      send-on-resolved: true
      failure-threshold: 5
      success-threshold: 2
connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m
default-endpoint: &defaults
  group: Internal
  interval: 2m
  conditions:
    - "[STATUS] == 200"
endpoints:
  # External
  - name: status
    group: External
    url: https://status.juicewizerd.com
    conditions:
      - "[STATUS] == 200"
      - "[STATUS] == any(200, 401)"
    alerts:
      - type: pushover
  - name: DNS Resolution
    group: server
    url: 192.168.1.1
    dns:
      query-name: auth.juicewizerd.com
      query-type: "A"
    conditions:
      - "[DNS_RCODE] == NOERROR"
  - name: Authelia
    group: External
    url: https://auth.juicewizerd.com/api/health
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "[STATUS] == any(200, 401)"
      - "[CERTIFICATE_EXPIRATION] > 48h"
  # Home Assistant
  - name: Home Assistant
    group: Home Assistant
    url: http://192.168.1.86:8123
    <<: *defaults
  - name: Zigbee2MQTT
    <<: *defaults
    group: Home Assistant
    url: http://192.168.1.86:8099
  - name: Frigate
    <<: *defaults
    group: Home Assistant
    url: http://192.168.1.91:5000/api/version
  - name: HASS DB
    group: Home Assistant
    <<: *defaults
    url: tcp://192.168.1.86:45678
  - name: Scrypted
    group: Home Assistant
    <<: *defaults
    url: http://192.168.1.91:11080
  # Internal
  - name: Grafana
    <<: *defaults
    url: http://192.168.1.242/api/health
  - name: Immich
    <<: *defaults
    url: http://192.168.1.93:2283/api/server-info/ping
  - name: LLDAP
    <<: *defaults
    url: http://192.168.1.243:17170/health
  # Media Server
  - name: Calibre-Web
    group: Media Server
    <<: *defaults
    url: http://192.168.1.93:8083
  - name: Jellyfin
    group: Media Server
    <<: *defaults
    url: http://192.168.1.92:8096/health
  - name: Kavita
    group: Media Server
    <<: *defaults
    url: http://192.168.1.93:5000/api/health
  - name: Miniflux
    group: Media Server
    <<: *defaults
    url: http://192.168.1.93:8089/healthcheck
  - name: Prowlarr
    group: Media Server
    <<: *defaults
    url: http://192.168.1.245/ping
  - name: qBittorrent
    group: Media Server
    <<: *defaults
    url: http://192.168.1.93:8060/
  - name: Radarr
    group: Media Server
    <<: *defaults
    url: http://192.168.1.93:7878/ping
  - name: SABnzbd
    group: Media Server
    <<: *defaults
    url: http://192.168.1.93:8080/api?mode=version
  - name: Sonarr
    group: Media Server
    <<: *defaults
    url: http://192.168.1.93:8989/ping
