---
web:
  port: ${CUSTOM_WEB_PORT}
storage:
  type: postgres
  path: postgres://${INIT_POSTGRES_USER}:${INIT_POSTGRES_PASS}@${INIT_POSTGRES_HOST}:5432/${INIT_POSTGRES_DBNAME}?sslmode=disable
  caching: true
metrics: false
debug: false
ui:
  title: Status | JuiceWizerd
  header: Status
alerting:
  pushover:
    application-token: ${CUSTOM_PUSHOVER_APP_TOKEN}
    user-key: ${CUSTOM_PUSHOVER_USER_KEY}
    default-alert:
      description: health-check failed
      send-on-resolved: true
      failure-threshold: 5
      success-threshold: 2
  ntfy:
    topic: uptime
    url: https://ntfy.juicewizerd.com
    token: ${NTFY_TOKEN}
    default-alert:
      description: health-check failed
      send-on-resolved: true
      failure-threshold: 5
      success-threshold: 2
connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m
default-endpoint: &defaults
  group: Internal
  interval: 2m
  conditions:
    - "[STATUS] == 200"
  alerts:
    - type: ntfy
endpoints:
  # External
  - name: DNS Resolution
    group: server
    url: 192.168.1.1
    dns:
      query-name: auth.juicewizerd.com
      query-type: "A"
    conditions:
      - "[DNS_RCODE] == NOERROR"
    alerts:
      - type: pushover
      - type: ntfy
  - name: Authelia
    group: External
    url: https://auth.juicewizerd.com/api/health
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
  - name: Authelia
    group: Internal
    url: http://authelia.default.svc.cluster.local/api/health
    conditions:
      - "[BODY].status == OK"
    alerts:
      - type: pushover
  # Home Assistant
  - name: Home Assistant
    group: Home Assistant
    url: http://192.168.1.86:8123
    <<: *defaults
  - name: Zigbee2MQTT
    <<: *defaults
    group: Home Assistant
    url: http://192.168.1.86:8099
  - name: Frigate
    <<: *defaults
    group: Home Assistant
    url: http://192.168.1.91:5000/api/version
  - name: Scrypted
    group: Home Assistant
    <<: *defaults
    url: http://192.168.1.91:11080
  # Internal
  - name: Grafana
    <<: *defaults
    url: http://192.168.1.242/api/health
    conditions:
      - "[BODY].database == ok"
  # - name: Immich
  #   <<: *defaults
  #   url: http://192.168.1.93:2283/api/server-info/ping
  #   conditions:
  #     - "[BODY].res == pong"
  # Media Server
  - name: Calibre-Web
    group: Media Server
    <<: *defaults
    url: http://192.168.1.93:8083
  - name: Jellyfin
    group: Media Server
    <<: *defaults
    url: http://192.168.1.92:8096/health
    conditions:
      - "[BODY] == Healthy"
  - name: Kavita
    group: Media Server
    <<: *defaults
    url: http://192.168.1.93:5000/api/health
    conditions:
      - "[BODY] == Ok"
  - name: Miniflux
    group: Media Server
    <<: *defaults
    url: http://192.168.1.93:8089/healthcheck
    conditions:
      - "[BODY] == OK"
  - name: qBittorrent
    group: Media Server
    <<: *defaults
    url: http://192.168.1.93:8060/
  - name: SABnzbd
    group: Media Server
    <<: *defaults
    url: http://192.168.1.93:8080/api?mode=version
  - name: Sonarr
    group: Media Server
    <<: *defaults
    url: http://192.168.1.93:8989/ping
    conditions:
      - "[BODY].status == OK"
    - name: Radarr
    group: Media Server
    <<: *defaults
    url: http://192.168.1.93:7878/ping
    conditions:
      - "[BODY].status == OK"
  # Databases
  - name: Prometheus
    group: Databases
    <<: *defaults
    url: http://192.168.1.93:9090/-/healthy
    conditions:
      - "[BODY] == Prometheus Server is Healthy."
  - name: InfluxDB - HAOS
    group: Databases
    <<: *defaults
    url: http://192.168.1.86:8086/health
    conditions:
      - "[BODY].status == pass"
      - "[BODY].message == ready for queries and writes"
  - name: InfluxDB - Main
    group: Databases
    <<: *defaults
    url: http://192.168.1.93:8086/health
    conditions:
      - "[BODY].status == pass"
      - "[BODY].message == ready for queries and writes"
