---
web:
  port: ${CUSTOM_WEB_PORT}
storage:
  type: postgres
  path: postgres://${INIT_POSTGRES_USER}:${INIT_POSTGRES_PASS}@${INIT_POSTGRES_HOST}:5432/${INIT_POSTGRES_DBNAME}?sslmode=disable
  caching: true
metrics: false
debug: false
ui:
  title: Status | Gatus
  header: Status
alerting:
  pushover:
    application-token: ${CUSTOM_PUSHOVER_APP_TOKEN}
    user-key: ${CUSTOM_PUSHOVER_USER_KEY}
    default-alert:
      description: health-check failed
      send-on-resolved: true
      failure-threshold: 5
      success-threshold: 2
connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m
endpoints:
  - name: status
    group: external
    url: https://status.juicewizerd.com
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: pushover
  - name: DNS Resolution
    group: server
    url: 192.168.1.1
    dns:
      query-name: auth.juicewizerd.com
      query-type: "A"
    conditions:
      - "[DNS_RCODE] == NOERROR"
  - name: Home Assistant
    group: internal
    url: http://192.168.1.86:8123
    conditions:
      - "[STATUS] == 200"
  - name: Zigbee2MQTT
    group: internal
    url: http://192.168.1.86:8099
    conditions:
      - "[STATUS] == 200"
  - name: Authelia
    group: external
    url: https://auth.juicewizerd.com/api/health
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "[STATUS] == 200"
