{
 "title": "Home Assistant - TimescaleDB",
 "tags": [
  "home",
  "climate",
  "timescale"
 ],
 "time": { "from": "now-36h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT \n  time_bucket('$__interval', time) as time,\n  entity_id,\n  avg(state_numeric)\nFROM ltss \nWHERE \n  $__timeFilter(\"time\") AND \n  state_numeric IS NOT NULL AND \n  entity_id LIKE '%temperature'\nGROUP BY 1, 2\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "rawSql": "SELECT \n  time_bucket('$__interval', time) as time,\n  entity_id,\n  avg(state_numeric)\nFROM ltss \nWHERE \n  $__timeFilter(\"time\") AND \n  state_numeric IS NOT NULL AND \n  entity_id LIKE '%humidity'\nGROUP BY 1, 2\nORDER BY time"
    }
   ]
  },
  {
   "title": "VOC Index",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT \n  time_bucket('$__interval', time) as time,\n  avg(state_numeric)\nFROM ltss \nWHERE \n  $__timeFilter(\"time\") AND \n  state_numeric IS NOT NULL AND \n  entity_id = 'sensor.living_room_climate_voc_index'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Particulate Matter Levels",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "µg/m³" } },
   "targets": [
    {
     "rawSql": "SELECT \n  time_bucket('$__interval', time) as time,\n  avg(state_numeric)\nFROM ltss \nWHERE \n  $__timeFilter(time) AND \n  state_numeric IS NOT NULL AND \n  entity_id = 'sensor.living_room_climate_pm25'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "rawSql": "SELECT \n  time_bucket('$__interval', time) as time,\n  entity_id,\n  avg(state_numeric) \nFROM ltss \nWHERE \n  $__timeFilter(\"time\") AND \n  state_numeric IS NOT NULL AND \n  entity_id LIKE '%pressure'\nGROUP BY 1, 2\nORDER BY time"
    }
   ]
  }
 ]
}