{
 "title": "Home Assistant - InfluxQL",
 "tags": [
  "home",
  "climate",
  "cloud",
  "influx"
 ],
 "time": { "from": "now-36h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "friendly_name::tag" ], "type": "tag" }
     ],
     "measurement": "°C",
     "query": "from(bucket: \"home_assistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"°C\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"friendly_name\"] != \"Living Room Climate temperature\")\r\n  |> map(fn: (r) => ({\r\n        _value: r._value, \r\n        _time: r._time, \r\n        name: \"${r[\"friendly_name\"]}\"\r\n    }))\r\n  |> group(columns: [\"name\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature Moving Average",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "friendly_name::tag" ], "type": "tag" }
     ],
     "measurement": "°C",
     "query": "from(bucket: \"home_assistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"°C\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"friendly_name\"] != \"Living Room Climate temperature\")\r\n  |> map(fn: (r) => ({\r\n        _value: r._value, \r\n        _time: r._time, \r\n        name: \"${r[\"friendly_name\"]}\"\r\n    }))\r\n  |> group(columns: [\"name\"])\r\n  // |> movingAverage(n: 20) \r\n  |> timedMovingAverage(every: 30m, period: 3h)\r\n  // |> aggregateWindow(every: 1h, fn: mean)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "3" ], "type": "moving_average" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "friendly_name::tag" ], "type": "tag" }
     ],
     "measurement": "%",
     "query": "from(bucket: \"home_assistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"%\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> map(fn: (r) => ({\r\n        _value: r._value, \r\n        _time: r._time, \r\n        name: \"${r[\"friendly_name\"]}\"\r\n    }))\r\n  |> group(columns: [\"name\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "VOC Index",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "sensor.living_room_climate_voc_index",
     "query": "from(bucket: \"home_assistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor.living_room_climate_voc_index\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> timedMovingAverage(every: 10m, period: 20m)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Particulate Matter Levels",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "µg/m³" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "friendly_name::tag" ], "type": "tag" }
     ],
     "measurement": "µg/m³",
     "query": "from(bucket: \"home_assistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"µg/m³\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> timedMovingAverage(every: 10m, period: 20m)\r\n  |> map(fn: (r) => ({\r\n        _value: r._value, \r\n        _time: r._time, \r\n        name: \"${r[\"friendly_name\"]}\"\r\n    }))\r\n  |> group(columns: [\"name\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "AC Sensor",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "friendly_name::tag" ], "type": "tag" }
     ],
     "measurement": "%",
     "query": "SELECT difference(last(\"value\")) FROM \"hass_rp\".\"%\" WHERE $timeFilter GROUP BY time(10m), \"friendly_name\"::tag",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "friendly_name::tag", "operator": "=", "value": "Living Room Climate humidity" }
     ]
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "friendly_name::tag" ], "type": "tag" }
     ],
     "measurement": "hPa",
     "query": "from(bucket: \"home_assistant\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> drop(columns: [\"source\"])\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hPa\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> map(fn: (r) => ({\n        _value: r._value, \n        _time: r._time, \n        name: \"${r[\"friendly_name\"]}\"\n    }))\n  |> group(columns: [\"name\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}