{
 "title": "Home Assistant - FlightSQL",
 "tags": [
  "home",
  "climate",
  "cloud",
  "influx"
 ],
 "time": { "from": "now-36h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "columns": [
      { "value": "time" },
      { "value": "value" },
      { "value": "friendly_name" }
     ],
     "orderBy": "time",
     "queryText": "SELECT \r\n  DATE_BIN(INTERVAL '$__interval_ms milliseconds', time) as time,\r\n  friendly_name ,\r\n  AVG(value)\r\nFROM \"°C\" \r\nWHERE \r\n  $__timeFilter(time)\r\nGROUP BY 1, 2\r\nORDER BY 1",
     "table": "\"°C\"",
     "wheres": [
      { "value": "$__timeFilter(time)" }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "columns": [
      { "value": "time" },
      { "value": "value" },
      { "value": "friendly_name" }
     ],
     "orderBy": "time",
     "queryText": "SELECT \r\n  DATE_BIN(INTERVAL '$__interval_ms milliseconds', time) as time,\r\n  friendly_name,\r\n  AVG(value)\r\nFROM \"%\" \r\nWHERE \r\n  $__timeFilter(time)\r\nGROUP BY 1, 2\r\nORDER BY 1",
     "table": "\"°C\"",
     "wheres": [
      { "value": "" }
     ]
    }
   ]
  },
  {
   "title": "VOC Index",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "columns": [
      { "value": "time" },
      { "value": "value" },
      { "value": "friendly_name" }
     ],
     "orderBy": "time",
     "queryText": "SELECT \n  DATE_BIN(INTERVAL '$__interval_ms milliseconds', time) as time,\n  AVG(value)\nFROM \"sensor.living_room_climate_voc_index\" \nWHERE $__timeFilter(time)\nGROUP BY 1\nORDER BY time",
     "table": "sensor.living_room_climate_voc_index",
     "wheres": [
      { "value": "" }
     ]
    }
   ]
  },
  {
   "title": "Particulate Matter Levels",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "columns": [
      { "value": "time" },
      { "value": "value" },
      { "value": "friendly_name" }
     ],
     "orderBy": "time",
     "queryText": "SELECT \n  DATE_BIN(INTERVAL '$__interval_ms milliseconds', time) as time,\n  AVG(value)\nFROM \"µg/m³\" \nWHERE $__timeFilter(time)\nGROUP BY 1\nORDER BY time",
     "table": "sensor.living_room_climate_voc_index",
     "wheres": [
      { "value": "" }
     ]
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "columns": [
      { "value": "time" },
      { "value": "value" },
      { "value": "friendly_name" }
     ],
     "orderBy": "time",
     "queryText": "SELECT \r\n  DATE_BIN(INTERVAL '$__interval_ms milliseconds', time) as time,\r\n  friendly_name,\r\n  AVG(value)\r\nFROM \"hPa\" \r\nWHERE \r\n  $__timeFilter(time)\r\nGROUP BY 1, 2\r\nORDER BY 1",
     "table": "\"°C\"",
     "wheres": [
      { "value": "" }
     ]
    }
   ]
  }
 ]
}