{
 "title": "AC Sensors",
 "tags": [
  "home",
  "climate",
  "influx",
  "prometheus"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "windowLength",
    "query": "20m,30m,40m,50m,60m,90m, 2h, 3h"
   }
  ]
 },
 "panels": [
  {
   "type": "gauge",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"home_assistant\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"°C\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"home_assistant\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"%\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> last()\n"
    }
   ]
  },
  {
   "title": "Influx AC Sensor",
   "type": "timeseries",
   "description": "Uses InfluxDB cloud",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "d1 = from(bucket: \"homeassistant\")\r\n      |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n      |> filter(fn: (r) => r[\"_measurement\"] == \"%\")\r\n      |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n      |> filter(fn: (r) => r[\"entity_id\"] == \"living_room_climate_humidity\")\r\n      |> window(every: 1m, period: ${windowLength})\r\n\r\nd2 = d1 |> first()\r\n\r\nd3 = d1 |> last()\r\n\r\nunion(tables: [d2, d3]) \r\n|> difference()\r\n|> window(period: inf)\r\n|> stateDuration(fn: (r) => r._value < -1)\r\n|> drop(columns: [\"_value\"])\r\n"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "from(bucket: \"home_assistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"%\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"living_room_climate_humidity\")"
    }
   ]
  },
  {
   "title": "Influx AC Sensor",
   "type": "timeseries",
   "description": "Uses InfluxDB cloud",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "d1 = from(bucket: \"homeassistant\")\r\n      |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n      |> filter(fn: (r) => r[\"_measurement\"] == \"%\")\r\n      |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n      |> filter(fn: (r) => r[\"entity_id\"] == \"living_room_climate_humidity\")\r\n      |> window(every: 1m, period: ${windowLength})\r\n\r\nd2 = d1 |> first()\r\n\r\nd3 = d1 |> last()\r\n\r\nunion(tables: [d2, d3]) \r\n|> difference()\r\n|> window(period: inf)\r\n|> aggregateWindow(every: 1m, fn: median)"
    }
   ]
  },
  {
   "title": "Humidity Difference",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "round(delta(hass_sensor_humidity_percent{friendly_name=\"Living Room Climate humidity\"}[${windowLength}]), 1)"
    }
   ]
  },
  {
   "title": "Influx AC Sensor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "query": "from(bucket: \"test_bucket\")\n      |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n      |> filter(fn: (r) => r[\"_measurement\"] == \"duration\")\n      |> filter(fn: (r) => r[\"_field\"] == \"value\")"
    }
   ]
  },
  {
   "title": "Prometheus Stored Humidity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "hass_sensor_humidity_percent{friendly_name=\"Living Room Climate humidity\"}"
    }
   ]
  }
 ]
}