{
 "title": "Energy",
 "tags": [
  "home",
  "energy",
  "influx"
 ],
 "time": { "from": "now-1y", "to": "now" },
 "panels": [
  {
   "title": "BIdgely Job Details",
   "type": "logs",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"default/bidgely\"} |= ``"
    }
   ]
  },
  {
   "title": "Current Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "first_over_time({job=\"default/bidgely\"} |= `Usage to Date:` | regexp `Usage to Date: (?P<price>.*) kWh` | unwrap price [24h])",
     "legendFormat": "{{ app }}"
    }
   ]
  },
  {
   "title": "Current Cost",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "first_over_time({job=\"default/bidgely\"} |= `Cost to Date:` | regexp `Cost to Date: \\$(?P<price>.*)` | unwrap price [1d])",
     "legendFormat": "{{ app }}"
    }
   ]
  },
  {
   "title": "Forecasted Cost",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "first_over_time({job=\"default/bidgely\"} |= `Forecasted Cost:` | regexp `Forecasted Cost: \\$(?P<price>.*)` | unwrap price [1d])",
     "legendFormat": "{{ app }}"
    }
   ]
  },
  {
   "title": "Daily Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"energy\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"bidgely\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage\")\r\n  |> aggregateWindow(every: 1d, fn: sum, offset: -20h)"
    },
    {
     "query": "from(bucket: \"energy\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"bidgely\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage\")\r\n  |> set(key: \"_field\", value: \"average\")\r\n  |> aggregateWindow(every: 1d, fn: sum)\r\n  |> movingAverage(n: 30)"
    },
    {
     "query": "from(bucket: \"energy\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"bidgely\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\r\n  |> aggregateWindow(every: 1d, fn: mean, offset: -20h)"
    }
   ]
  },
  {
   "title": "Weekly Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"energy\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"bidgely\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage\")\r\n  |> aggregateWindow(every: 1w, fn: sum, offset: -4d)"
    }
   ]
  },
  {
   "title": "Monthly Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"energy\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"bidgely\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage\")\r\n  |> aggregateWindow(every: 1mo, fn: sum)"
    }
   ]
  }
 ]
}