{
 "title": "Media Dashboard",
 "tags": [
  "media",
  "server"
 ],
 "time": { "from": "now-14d", "to": "now" },
 "refresh": "1h",
 "panels": [
  { "title": "Sonarr", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sonarr_system_status\n", "legendFormat": "Status" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sonarr_queue_total", "legendFormat": "Queued" },
    { "expr": "sonarr_history_total", "legendFormat": "History" },
    {
     "expr": "sonarr_episode_downloaded_total",
     "legendFormat": "Downloaded"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(sonarr_series_monitored_total)",
     "legendFormat": "Series Monitored"
    },
    { "expr": "max(sonarr_series_total)", "legendFormat": "Series Total" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(sonarr_season_monitored_total)",
     "legendFormat": "Seasons Monitored"
    },
    { "expr": "max(sonarr_season_total)", "legendFormat": "Seasons Total" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(sonarr_episode_missing_total)",
     "legendFormat": "Episodes Missing"
    },
    { "expr": "max(sonarr_episode_total)", "legendFormat": "Episodes Total" }
   ]
  },
  {
   "title": "Qualities",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sonarr_episode_quality_total", "legendFormat": "{{quality}}" }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "sonarr_series_filesize_bytes", "legendFormat": "Used" }
   ]
  },
  {
   "title": "System Health Issues",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "targets": [
    { "expr": "sonarr_system_health_issues", "legendFormat": "__auto" }
   ]
  },
  { "title": "Radarr", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "radarr_system_status\n", "legendFormat": "Status" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 3, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "radarr_movie_downloaded_total", "legendFormat": "Downloaded" },
    { "expr": "radarr_movie_monitored_total", "legendFormat": "Monitored" },
    { "expr": "radarr_movie_wanted_total", "legendFormat": "Wanted" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "radarr_queue_total", "legendFormat": "Queued" },
    { "expr": "radarr_movie_downloaded_total", "legendFormat": "Downloaded" },
    { "expr": "radarr_history_total", "legendFormat": "History" },
    { "expr": "radarr_movie_filesize_total", "legendFormat": "Disk Used" },
    {
     "expr": "radarr_rootfolder_freespace_bytes",
     "legendFormat": "Disk Free"
    }
   ]
  },
  {
   "title": "Qualities",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "radarr_movie_quality_total", "legendFormat": "{{quality}}" }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "radarr_movie_filesize_total", "legendFormat": "Used" }
   ]
  },
  {
   "title": "System Health Issues",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "targets": [
    { "expr": "radarr_system_health_issues", "legendFormat": "__auto" }
   ]
  },
  { "title": "Prowlarr", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "prowlarr_system_status\n", "legendFormat": "Status" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 3, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(prowlarr_system_health_issues)",
     "legendFormat": "Health Issues"
    },
    {
     "expr": "max(prowlarr_indexer_enabled_total)",
     "legendFormat": "Enabled Indexers"
    },
    {
     "expr": "max(prowlarr_indexer_total - prowlarr_indexer_enabled_total)",
     "legendFormat": "Disabled Indexers"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prowlarr_indexer_queries_total[$__range]))",
     "legendFormat": "Queries"
    },
    {
     "expr": "sum(increase(prowlarr_indexer_grabs_total[$__range]))",
     "legendFormat": "Grabs"
    },
    {
     "expr": "sum(increase(prowlarr_indexer_failed_queries_total[$__range]))",
     "legendFormat": "Query Failures"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 16, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(prowlarr_indexer_average_response_time_ms)",
     "legendFormat": "Response Time"
    },
    {
     "expr": "sum(increase(prowlarr_indexer_failed_queries_total[$__range])) / sum(prowlarr_indexer_queries_total)",
     "legendFormat": "Failed Queries"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(prowlarr_indexer_vip_expires_in_seconds)",
     "legendFormat": "Nearest VIP Expiration"
    }
   ]
  },
  {
   "title": "Indexer Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(prowlarr_indexer_average_response_time_ms) by (indexer)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User Agent Queries",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(increase(prowlarr_user_agent_queries_total[$__rate_interval])) by (user_agent)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queries by Indexer",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prowlarr_indexer_queries_total[$__range])) by (indexer)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grabs by Indexer",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prowlarr_indexer_grabs_total[$__range])) by (indexer)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queries by User Agent",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prowlarr_user_agent_queries_total[$__range])) by (user_agent)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grabs by User Agent",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prowlarr_user_agent_grabs_total[$__range])) by (user_agent)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VIP Expiration",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "prowlarr_indexer_vip_expires_in_seconds",
     "legendFormat": "__auto"
    },
    {
     "expr": "(time() * 1000) + (prowlarr_indexer_vip_expires_in_seconds * 1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Health Issues",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 71 },
   "targets": [
    { "expr": "prowlarr_system_health_issues", "legendFormat": "__auto" }
   ]
  },
  { "title": "Sabnzbd", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Downloads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 15, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(sabnzbd_downloaded_bytes)", "legendFormat": "Lifetime" },
    {
     "expr": "max(increase(sabnzbd_downloaded_bytes[$__range]))",
     "legendFormat": "Recent"
    },
    { "expr": "sabnzbd_queue_length", "legendFormat": "Queued" },
    { "expr": "sabnzbd_total_bytes", "legendFormat": "Queue Size" },
    { "expr": "sabnzbd_remaining_bytes", "legendFormat": "Remaining" },
    {
     "expr": "sum(sabnzbd_server_articles_success) / sum(sabnzbd_server_articles_total)",
     "legendFormat": "Success Rate"
    }
   ]
  },
  {
   "title": "Quota",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 79 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sabnzbd_quota_bytes\n", "legendFormat": "Size" },
    {
     "expr": "1 - max(sabnzbd_remaining_quota_bytes / sabnzbd_quota_bytes)",
     "legendFormat": "Usage"
    },
    { "expr": "sabnzbd_remaining_quota_bytes", "legendFormat": "Remaining" }
   ]
  },
  {
   "title": "Cache",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sabnzbd_article_cache_articles", "legendFormat": "Articles" },
    { "expr": "sabnzbd_article_cache_bytes", "legendFormat": "Size" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 83 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"sabnzbd\"}",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{container=\"sabnzbd\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sabnzbd_status", "legendFormat": "Mode" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sabnzbd_time_estimate_seconds", "legendFormat": "Time Remaining" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sabnzbd_speed_bps", "legendFormat": "D/L Speed" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 15, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sabnzbd_paused_all", "legendFormat": "Hard Pause" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sabnzbd_pause_duration_seconds", "legendFormat": "Resume In" }
   ]
  },
  {
   "title": "Disk Used",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(sabnzbd_disk_used_bytes{folder=\"download\"} / sabnzbd_disk_total_bytes{folder=\"download\"})",
     "legendFormat": "Download"
    },
    {
     "expr": "min(sabnzbd_disk_used_bytes{folder=\"complete\"} / sabnzbd_disk_total_bytes{folder=\"complete\"})",
     "legendFormat": "Complete"
    }
   ]
  },
  {
   "title": "Download Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "avg(increase(sabnzbd_server_downloaded_bytes[$__rate_interval])) by (server)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{pod=~\"sabnzbd.*\"}[$__rate_interval]))",
     "legendFormat": "Network Transmit"
    },
    {
     "expr": "sum(irate(container_network_receive_bytes_total{pod=~\"sabnzbd.*\"}[$__rate_interval])) * -1",
     "legendFormat": "Network Receive"
    }
   ]
  },
  {
   "title": "Lifetime Downloads By Server",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sabnzbd_server_downloaded_bytes",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Recent Downloaded By Server",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(increase(sabnzbd_server_downloaded_bytes[$__range])) by (server)",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Recent Download Percent",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(increase(sabnzbd_server_downloaded_bytes[$__range])) by (server)",
     "legendFormat": "{{server}}"
    }
   ]
  }
 ]
}