{
 "title": "Proxmox Prometheus",
 "tags": [
  "server",
  "proxmox"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "host", "label": "Proxmox Host", "query": "chihiro, haku" }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "avg_over_time(cpustat_cpu[1m])", "legendFormat": "{{host}}" }
   ]
  },
  {
   "title": "CPU Temp",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg_over_time(sensors_temp_input{chip=\"coretemp-isa-0000\", feature=\"package_id_0\"}[1m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Guest CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time(system_cpu{instance=\"$host\", host!=\"debian-template\"}[$__interval])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Guest Claimed Memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "system_mem{instance=\"$host\", host!=\"debian-template\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Guest Download Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(nics_netin{instance=\"chihiro\"}[1m])",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}