{
 "title": "Proxmox",
 "tags": [
  "server",
  "proxmox"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "host", "label": "Proxmox Host", "query": "chihiro, haku" }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "query": "from(bucket: \"proxmox\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpustat\")\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu\")\n  // |> filter(fn: (r) => r[\"host\"] == \"${host}\")\n  |> keep(columns: [\"host\", \"_time\", \"_value\"])\n  |> aggregateWindow(every: 1m, fn: mean)\n  \n"
    }
   ]
  },
  {
   "title": "CPU Temp",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"proxmox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensors\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temp_input\")\r\n  // |> filter(fn: (r) => r[\"host\"] == \"${host}\")\r\n  |> filter(fn: (r) => r[\"chip\"] == \"coretemp-isa-0000\")\r\n  |> filter(fn: (r) => r[\"feature\"] == \"package_id_0\")\r\n  |> keep(columns: [\"host\", \"_time\", \"_value\"])\r\n  |> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "Guest CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "query": "from(bucket: \"proxmox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu\")\r\n  |> filter(fn: (r) => r[\"nodename\"] == \"${host}\")\r\n  |> filter(fn: (r) => r[\"host\"] != \"debian-template\")\r\n  |> keep(columns: [\"host\", \"_time\", \"_value\"])\r\n  |> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "Guest Claimed Memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"proxmox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mem\")\r\n  |> filter(fn: (r) => r[\"nodename\"] == \"${host}\")\r\n  |> filter(fn: (r) => r[\"host\"] != \"debian-template\")\r\n  |> keep(columns: [\"host\", \"_time\", \"_value\"])\r\n  |> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "Guest Download Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "query": "from(bucket: \"proxmox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nics\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"netin\")\r\n  |> filter(fn: (r) => r[\"nodename\"] == \"${host}\")\r\n  |> derivative(unit: 1s, nonNegative: false)\r\n  |> keep(columns: [\"host\", \"_time\", \"_value\"])"
    }
   ]
  }
 ]
}