---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatus
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "7"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://bjw-s.github.io/helm-charts
      chart: app-template
      targetRevision: 2.5.0
      helm:
        valuesObject:
          controllers:
            main:
              annotations:
                reloader.stakater.com/auto: "true"
              containers:
                main:
                  image:
                    repository: ghcr.io/twin/gatus
                    tag: v5.7.0
                  envFrom: &envFrom
                    - secretRef:
                        name: "gatus-secret"
                  env:
                    TZ: America/Toronto
                    GATUS_CONFIG_PATH: /config
                    CUSTOM_WEB_PORT: &port 80
              initContainers:
                01-init-db:
                  image:
                    repository: ghcr.io/onedr0p/postgres-init
                    tag: 16.1
                  envFrom: *envFrom
                02-config-sync:
                  image:
                    repository: ghcr.io/kiwigrid/k8s-sidecar
                    tag: 1.25.3
                  imagePullPolicy: IfNotPresent
                  env:
                    - { name: FOLDER, value: /config }
                    - { name: LABEL, value: gatus.io/enabled }
                    - { name: NAMESPACE, value: ALL }
                    - { name: RESOURCE, value: both }
                    - { name: UNIQUE_FILENAMES, value: "true" }
                    - { name: METHOD, value: LIST }
                  volumeMounts:
                    - { name: config, mountPath: /config }
          sidecars:
            config-sync:
              image:
                repository: ghcr.io/kiwigrid/k8s-sidecar
                tag: 1.25.3
              imagePullPolicy: IfNotPresent
              env:
                - { name: FOLDER, value: /config }
                - { name: LABEL, value: gatus.io/enabled }
                - { name: NAMESPACE, value: ALL }
                - { name: RESOURCE, value: both }
                - { name: UNIQUE_FILENAMES, value: "true" }
                - { name: METHOD, value: WATCH }
              volumeMounts:
                - { name: config, mountPath: /config }
          serviceAccount:
            name: gatus
          service:
            main:
              ports:
                http:
                  port: *port
          ingress:
            main:
              enabled: true
              classNme: traefik
              annotations:
                traefik.ingress.kubernetes.io/router.entrypoints: websecure
                traefik.ingress.kubernetes.io/router.middlewares: default-crowdsec-authelia@kubernetescrd
              hosts:
                - host: &host status.juicewizerd.com
                  paths:
                    - path: /
                      pathType: Prefix
                      service:
                        name: main
                        port: http
              tls:
                - hosts:
                    - *host
                  secretName: juicewizerd-le-com-tls
          persistence:
            config:
              enabled: true
              type: emptyDir
            config-file:
              enabled: true
              type: configMap
              name: gatus-configmap
              advancedMounts:
                main:
                  main:
                    - path: /config/config.yaml
                      readOnly: true
                      subPath: config.yaml

    - repoURL: "https://github.com/carterjgreen/home-server.git"
      path: manifests/gatus
      targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
