---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: grafana
      targetRevision: 6.58.7
      helm:
        # valueFiles:
        #   - $myRepo/manifests/grafana/values.yaml
        values: |
          service:
            type: LoadBalancer
            annotations:
              metallb.universe.tf/loadBalancerIPs: 192.168.1.242

          resources:
            limits:
              cpu: 250m
              memory: 750Mi
            requests:
              cpu: 100m
              memory: 128Mi

          persistence:
            enabled: true
            size: 1Gi

          admin:
            existingSecret: "grafana"

          envFromSecret: "grafana"

          plugins:
            - influxdata-flightsql-datasource

          datasources:
            datasources.yaml:
              apiVersion: 1
              datasources:
                - name: Prometheus
                  type: prometheus
                  url: http://192.168.1.93:9090
                - name: InfluxDB
                  type: influxdb
                  isDefault: true
                  url: http://192.168.1.93:8086
                  jsonData:
                    version: Flux
                    organization: my-org
                    defaultBucket: home_assistant
                    tlsSkipVerify: true
                  secureJsonData:
                    token: ${influx-token}

          grafana.ini:
            server:
              root_url: https://graf.juicewizerd.com
              enable_gzip: true
            auth:
              oauth_auto_login: true
            auth.basic:
              enabled: false
            auth.anonymous:
              enabled: false
            auth.generic_oauth:
              enabled: true
              name: Authelia
              client_id: grafana
              scopes: openid profile email groups
              empty_scopes: false
              auth_url: https://auth.juicewizerd.com/api/oidc/authorization
              token_url: https://auth.juicewizerd.com/api/oidc/token
              api_url: https://auth.juicewizerd.com/api/oidc/userinfo
              login_attribute_path: preferred_username
              groups_attribute_path: groups
              name_attribute_path: name
              use_pkce: true
              allow_assign_grafana_admin: true
              role_attribute_path: |
                contains(groups[*], 'admin') && 'Admin' || contains(groups[*], 'people') && 'Viewer'
            analytics:
              reporting_enabled: false
              check_for_updates: false
              check_for_plugin_updates: false
    - repoURL: https://github.com/carterjgreen/home-server.git
      path: manifests/grafana
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
