---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-agent-flow
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: grafana-agent
      targetRevision: 0.19.0
      helm:
        values: | # config.river
          agent:
            configMap:
              content: |
                prometheus.remote_write "off_cluster" {
                  endpoint {
                    url = "http://192.168.1.93:9090/api/v1/write"
                  }
                }

                prometheus.operator.podmonitors "pods" {
                    forward_to = [prometheus.remote_write.off_cluster.receiver]
                }

                prometheus.operator.servicemonitors "services" {
                    forward_to = [prometheus.remote_write.off_cluster.receiver]
                }

                prometheus.scrape "proxmox_scraper" {
                  targets = [
                    {"__address__" = "192.168.1.97:9273", "instance" = "chihiro"},
                    {"__address__" = "192.168.1.98:9273", "instance" = "haku"},
                  ]

                  forward_to = [prometheus.remote_write.off_cluster.receiver]

                  scrape_interval = "10s"
                }

            enableReporting: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
