---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: grafana
      targetRevision: 7.0.6
      helm:
        valuesObject:
          annotations:
            reloader.stakater.com/auto: "true"
          service:
            type: LoadBalancer
            annotations:
              metallb.universe.tf/loadBalancerIPs: 192.168.1.242
          serviceMonitor:
            enabled: true
          ingress:
            enabled: true
            ingressClassName: traefik
            annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: websecure
              traefik.ingress.kubernetes.io/router.middlewares: default-crowdsec-authelia@kubernetescrd
            hosts:
              - &host graf.juicewizerd.com
            tls:
              - secretName: juicewizerd-le-com-tls
                hosts:
                  - *host
          resources:
            limits:
              cpu: 250m
              memory: 750Mi
            requests:
              cpu: 100m
              memory: 128Mi
          persistence:
            enabled: true
            size: 1Gi
          admin:
            existingSecret: "grafana"
            userKey: "ADMIN-USER"
            passwordKey: ADMIN-PASSWORD
          envFromSecret: "grafana"
          plugins:
            - influxdata-flightsql-datasource
          datasources:
            datasources.yaml:
              apiVersion: 1
              datasources:
                - name: Prometheus
                  type: prometheus
                  url: http://192.168.1.93:9090
                - name: InfluxDB
                  type: influxdb
                  isDefault: true
                  url: http://192.168.1.93:8086
                  jsonData:
                    version: Flux
                    organization: my-org
                    defaultBucket: home_assistant
                    tlsSkipVerify: true
                  secureJsonData:
                    token: ${INFLUX-TOKEN}
                - name: TimescaleDB
                  type: postgres
                  url: 192.168.1.86:45678
                  user: grafana
                  secureJsonData:
                    password: ${TIMESCALE-PASSWORD}
                  jsonData:
                    database: homeassistant
                    sslmode: "disable"
                    postgresVersion: 15
                    timescaledb: true
                - name: Loki
                  type: loki
                  url: http://loki-headless:3100
          grafana.ini:
            server:
              root_url: https://graf.juicewizerd.com
              enable_gzip: true
            auth:
              oauth_auto_login: true
              oauth_allow_insecure_email_lookup: true
            auth.basic:
              enabled: false
            auth.anonymous:
              enabled: false
            auth.generic_oauth:
              enabled: true
              name: Authelia
              icon: signin
              client_id: grafana
              scopes: openid profile email groups
              empty_scopes: false
              auth_url: https://auth.juicewizerd.com/api/oidc/authorization
              token_url: https://auth.juicewizerd.com/api/oidc/token
              api_url: https://auth.juicewizerd.com/api/oidc/userinfo
              login_attribute_path: preferred_username
              groups_attribute_path: groups
              name_attribute_path: name
              use_pkce: true
              allow_assign_grafana_admin: true
              role_attribute_path: |
                contains(groups[*], 'GrafanaAdmin') && 'GrafanaAdmin' || groups[*], 'admin') && 'Admin' || contains(groups[*], 'people') && 'Viewer'
              skip_org_role_sync: true
            analytics:
              reporting_enabled: false
              check_for_updates: false
              check_for_plugin_updates: false
    - repoURL: https://github.com/carterjgreen/home-server.git
      path: manifests/grafana
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
