---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-alloy
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: alloy
      targetRevision: 0.12.6
      helm:
        valuesObject:
          controller:
            type: statefulset
          alloy:
            clustering:
              enabled: true
            configMap:
              content: |
                prometheus.remote_write "off_cluster" {
                  endpoint {
                    url = "http://192.168.1.93:9090/api/v1/write"
                  }
                }

                prometheus.operator.podmonitors "pods" {
                  forward_to = [prometheus.remote_write.off_cluster.receiver]
                  clustering {
                    enabled = true
                  }
                }

                prometheus.operator.servicemonitors "services" {
                  forward_to = [prometheus.remote_write.off_cluster.receiver]
                  clustering {
                    enabled = true
                  }
                }

                prometheus.scrape "proxmox_scraper" {
                  clustering {
                    enabled = true
                  }
                  targets = [
                    {"__address__" = "192.168.1.97:9273", "instance" = "chihiro"},
                    {"__address__" = "192.168.1.98:9273", "instance" = "haku"},
                  ]

                  forward_to = [prometheus.remote_write.off_cluster.receiver]

                  scrape_interval = "10s"
                }
            enableReporting: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
