---
apiVersion: v1
kind: Service
metadata:
  name: unpoller
spec:
  type: ClusterIP
  selector:
    app: unpoller
  ports:
    - name: unpoller-out
      protocol: TCP
      port: 9130
      targetPort: unpoller-prom
