---
# apiVersion: v1
# kind: Service
# metadata:
#   name: sonarr-exporter
# spec:
#   type: ClusterIP
#   selector:
#     app: sonarr-exporter
#   ports:
#     - name: sonarr
#       protocol: TCP
#       port: 9707
#       targetPort: sonarr-prom
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: sonarr-exporter
spec:
  selector:
    matchLabels:
      app: sonarr-exporter
  podMetricsEndpoints:
    - port: sonarr-prom
---
apiVersion: v1
kind: Service
metadata:
  name: radarr-exporter
spec:
  type: ClusterIP
  selector:
    app: radarr-exporter
  ports:
    - name: radarr
      protocol: TCP
      port: 9708
      targetPort: radarr-prom
---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr-exporter
spec:
  type: ClusterIP
  selector:
    app: prowlarr-exporter
  ports:
    - name: prowlarr
      protocol: TCP
      port: 9710
      targetPort: prowlarr-prom
---
apiVersion: v1
kind: Service
metadata:
  name: sabnzbd-exporter
spec:
  type: ClusterIP
  selector:
    app: sabnzbd-exporter
  ports:
    - name: sabnzbd
      protocol: TCP
      port: 9712
      targetPort: sabnzbd-prom
---
apiVersion: v1
kind: Service
metadata:
  name: nuts-exporter
spec:
  type: ClusterIP
  selector:
    app: nuts-exporter
  ports:
    - name: nuts
      protocol: TCP
      port: 9199
      targetPort: nuts-prom
