---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: sonarr-exporter
spec:
  selector:
    matchLabels:
      app: sonarr-exporter
  podMetricsEndpoints:
    - port: sonarr-prom
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: radarr-exporter
spec:
  selector:
    matchLabels:
      app: radarr-exporter
  podMetricsEndpoints:
    - port: radarr-prom
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: prowlarr-exporter
spec:
  selector:
    matchLabels:
      app: prowlarr-exporter
  podMetricsEndpoints:
    - port: prowlarr-prom
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: sabnzbd-exporter
spec:
  selector:
    matchLabels:
      app: sabnzbd-exporter
  podMetricsEndpoints:
    - port: sabnzbd-prom
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: nuts-exporter
spec:
  selector:
    matchLabels:
      app: nuts-exporter
  podMetricsEndpoints:
    - port: nuts-prom
