apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguardhome-sync
  labels:
    app: adguardhome-sync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sync-pod
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sync-pod
    spec:
      containers:
        - name: sync
          image: lscr.io/linuxserver/adguardhome-sync:0.4.14
          env:
            - name: TZ
              value: America/Toronto
            - name: API_PORT
              value: "0"
            - name: CRON
              value: "*/10 * * * *"
            - name: RUNONSTART
              value: "true"
            - name: ORIGIN_URL
              value: "http://192.168.1.93:8070"
            - name: ORIGIN_USERNAME
              value: "carter"
            - name: ORIGIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: adguard
                  key: ORIGIN_PASSWORD
            - name: REPLICA1_URL
              value: "http://192.168.1.99:8070"
            - name: REPLICA1_USERNAME
              value: carter
            - name: REPLICA1_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: adguard
                  key: REPLICA_PASSWORD
            - name: REPLICA_URL
              value: "http://192.168.1.86:3010"
            - name: REPLICA_USERNAME
              value: "external"
            - name: REPLICA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: adguard
                  key: REPLICA1_PASSWORD
          resources:
            limits:
              memory: 100Mi
              cpu: 100m
