apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: k3s
        envSlug: dev
        secretsPath: "/cert-manager"
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: default
  managedSecretReference:
    secretName: cloudflare-token-secret
    secretNamespace: cert-manager
