apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  resyncInterval: 60
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: service-token
        secretNamespace: default
      secretsScope:
        envSlug: dev
        secretsPath: "/cert-manager"
  managedSecretReference:
    secretName: cloudflare-token-secret
    secretNamespace: cert-manager
