---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: juicewizerd-le-com
  namespace: default
spec:
  secretName: juicewizerd-le-com-tls
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
  commonName: "*.juicewizerd.com"
  dnsNames:
    - "juicewizerd.com"
    - "*.juicewizerd.com"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "default,monitoring"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "default,monitoring"
