---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authelia
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    # https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/#helm-value-files-from-external-git-repository
    - repoURL: https://charts.authelia.com/
      chart: authelia
      targetRevision: 0.8.57
      helm:
        releaseName: authelia
        valueFiles:
          - $myRepo/manifests/authelia/authelia-values.yaml
    - repoURL: https://github.com/carterjgreen/home-server.git
      ref: myRepo
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamsepace=true
