---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lldap
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://github.com/carterjgreen/home-server.git"
    path: manifests/lldap
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: lldap
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamsepace=true
