---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - gatus-rbac.yaml
configMapGenerator:
  - name: gatus-configmap
    files:
      - ./config/config.yaml
generatorOptions:
  disableNameSuffixHash: true
