---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana-deployment.yaml # deployment definition
  - grafana-svc.yaml # service connecting pods to cluster network
  - grafana-pvc.yaml # pvc used to store cache and attachment
  - grafana-ingress.yaml # ingress definition
configMapGenerator:
  - name: grafana-config
    files:
      - grafana.ini
namespace: default # select namespace for whole application
