---
## Repository: authelia https://charts.authelia.com
## Chart: authelia

domain: juicewizerd.com

ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: traefik-external
  tls:
    secret: juicewizerd-com-tls
  traefikCRD:
    enabled: true
    entryPoints:
      - web
      - websecure
    # sticky: true
pod:
  kind: DaemonSet # Must be Deployment, DaemonSet, or StatefulSet.
  strategy:
    type: RollingUpdate

  env:
  - name: TZ
    value: America/Toronto

  resources:
    limits:
      cpu: "4.00"
      memory: 125Mi
    requests:
      cpu: "0.25"
      memory: 50Mi

## Authelia Config Map Generator
configMap:
  enabled: true
  key: configuration.yaml

  server:
    host: 0.0.0.0
    port: 9091
    buffers:
      read: 10485760 # Set large for calibre web
      write: 8192
  log:
    level: info
    keep_stdout: true
  default_redirection_url: https://auth.juicewizerd.com
  theme: auto   # options: dark, light, grey, auto
  totp:
    disable: false
    issuer: juicewizerd.com
    algorithm: sha1
    digits: 6
    period: 30
    skew: 1
    secret_size: 32

  authentication_backend:
    password_reset:
      disable: false
    refresh_interval: 1m
    ldap:
      implementation: custom
      url: ldap://lldap-service.lldap.svc.cluster.local:3890
      timeout: 5s
      start_tls: false
      base_dn: dc=juicewizerd,dc=com
      username_attribute: uid
      additional_users_dn: ou=people
      users_filter: "(&(|({username_attribute}={input})({mail_attribute}={input}))(objectClass=person))"
      additional_groups_dn: ou=groups
      groups_filter: "(member={dn})"
      group_name_attribute: cn
      mail_attribute: mail
      display_name_attribute: displayName
      user: uid=admin,ou=people,dc=juicewizerd,dc=com

  access_control:
    default_policy: deny
    rules:
      # # Already hass 2FA
      - domain:
          - "hass.juicewizerd.com"
        policy: bypass
      # Kobo bypass
      - domain: "books.juicewizerd.com"
        policy: bypass
        resources:
          - "^/kobo([/?].*)?$"
      # Home assistant app bypass
      - domain: 
          - "hass.juicewizerd.com"
        policy: bypass
        resources:
          - '^/api([/?].*)?$'
          - "^/auth/token.*"
          - "^/.external_auth=.*"
          - "^/service_worker.js"
          - "^/static.*"
          - "^/local.*"
          - "^/hacsfiles.*"
          - "^/frontend_latest.*"
      # Uptime-Kuma API
      - domain: 
          - "uptime.juicewizerd.com"
        policy: bypass
        resources:
          - '^/api([/?].*)?$'
      ## Two-Factor
      - domain: 
          - "homer.juicewizerd.com"
        policy: two_factor
      ## One-Factor
      - domain:
          - "*.juicewizerd.com"
          # - "uptime.juicewizerd.com"
          # - "books.juicewizerd.com"
          # - "whoami.juicewizerd.com"
        policy: one_factor 
          
  session:
    name: authelia_session
    domain: juicewizerd.com 
    expiration: 1h
    inactivity: 2h
    redis:
      host: 192.168.1.99

  regulation:
    max_retries: 5
    find_time: 120
    ban_time: 300

  storage:
    postgres:
      host: 192.168.1.99
      port: 5433

      
  notifier:
    filesystem:
      enabled: true
      filename: /config/notification.txt
    smtp:
      enabled: false

secret:
  existingSecret: authelia

persistence:
  enabled: false
  existingClaim: "authelia-pvc"
  storageClass: "longhorn"
