apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authelia-pvc
  namespace: databases
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi