---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - recyclarr-deployment.yaml
configMapGenerator:
  - name: sonarr-config
    files:
      - sonarr.yaml
  - name: radarr-config
    files:
      - radarr.yaml
namespace: default
