---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: recyclarr
  labels:
    app: recyclarr
spec:
  schedule: "@daily"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: sync
              image: ghcr.io/recyclarr/recyclarr:7.0.0
              command: ["recyclarr"]
              args:
                - "sync"
              env:
                - name: TZ
                  value: America/Toronto
              envFrom:
                - secretRef:
                    name: starr
              resources:
                limits:
                  memory: 500Mi
                  cpu: 1000m
              volumeMounts:
                - mountPath: /config/configs/sonarr.yaml
                  subPath: sonarr.yaml
                  name: sonarr-volume
                  readOnly: true
                - mountPath: /config/configs/radarr.yaml
                  subPath: radarr.yaml
                  name: radarr-volume
                  readOnly: true
                - mountPath: /config
                  name: cache-volume
          volumes:
            - name: sonarr-volume
              configMap:
                name: sonarr-config
            - name: radarr-volume
              configMap:
                name: radarr-config
            - name: cache-volume
              persistentVolumeClaim:
                claimName: recyclarr-pvc
          restartPolicy: OnFailure
