alertmanager:
  enabled: false

prometheus-pushgateway:
  enabled: false

kube-state-metrics:
  enabled: false

server:
  remoteWrite:
    - url: http://192.168.1.93:9090/api/v1/write

extraScrapeConfigs: |
  - job_name: 'unifipoller'
    scrape_interval: 30s
    static_configs:
    - targets: ['unpoller:9130']