apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: hydro-ottawa
spec:
  resyncInterval: 60
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: service-token
        secretNamespace: default
      secretsScope:
        envSlug: dev
        secretsPath: "/hydro_ottawa"
  managedSecretReference:
    secretName: hydro-ottawa
    secretNamespace: default
