apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: hydro-ottawa
spec:
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: k3s-f6-lw
        envSlug: dev
        secretsPath: "/hydro_ottawa"
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: default
  managedSecretReference:
    secretName: hydro-ottawa
    secretNamespace: default
