---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hydro-ottawa
  labels:
    app: hydro-ottawa
spec:
  schedule: "5 6 * * *"
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 4
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hydro-ottawa
              image: hydro-ottawa
              imagePullPolicy: Never
              env:
                - name: TZ
                  value: America/Toronto
              envFrom:
                - secretRef:
                    name: hydro-ottawa
              resources:
                limits:
                  memory: 100Mi
                  cpu: 100m
          restartPolicy: "OnFailure"
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: kubernetes.io/hostname
                        operator: In
                        values:
                          - zeniba
