---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hass
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - &host hass.juicewizerd.com
      secretName: juicewizerd-le-com-tls
  rules:
    - host: *host
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: hass
                port:
                  number: 8123
---
apiVersion: v1
kind: Service
metadata:
  name: hass
  namespace: default
spec:
  externalName: 192.168.1.86
  type: ExternalName
  ports:
    - port: 8123
