---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jellyfin
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`jellyfin.juicewizerd.com`)
      kind: Rule
      services:
        - kind: Service
          name: jellyfin
          namespace: default
          port: 8096
      middlewares:
        - name: local-allowlist
  tls:
    secretName: juicewizerd-le-com-tls
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: default
spec:
  externalName: 192.168.1.92
  type: ExternalName
  ports:
    - port: 8096
