---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uptime
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: default-authelia-2fa@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - &host uptime2.juicewizerd.com
      secretName: juicewizerd-le-com-tls
  rules:
    - host: *host
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: uptime
                port:
                  number: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: uptime
  namespace: default
spec:
  externalName: 192.168.1.86
  type: ExternalName
  ports:
    - port: 3001
