{
 "title": "Energy",
 "tags": [
  "home",
  "energy"
 ],
 "time": { "from": "2020-07-06T04:00:00.000Z", "to": "now" },
 "refresh": "1d",
 "panels": [
  {
   "title": "Daily Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "decimalSeparator": ".",
     "delimiter": ",",
     "query": "from(bucket: \"energy\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> aggregateWindow(every: 1d, fn: sum)",
     "schema": [
      { "name": "", "type": "string" }
     ]
    },
    {
     "query": "from(bucket: \"energy\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> aggregateWindow(every: 1d, fn: sum)\r\n  |> movingAverage(n: 30)"
    }
   ]
  },
  {
   "title": "Weekly Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"energy\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> aggregateWindow(every: 1w, fn: sum)"
    }
   ]
  },
  {
   "title": "Monthly Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"energy\")\r\n  |> range(start: 2020-07-01, stop:v.timeRangeStop)\r\n  |> aggregateWindow(every: 1mo, fn: sum)"
    }
   ]
  }
 ]
}