{
 "title": "Grocery",
 "time": { "from": "now/M", "to": "now" },
 "panels": [
  {
   "title": "Total Cost",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"grocery\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> drop(columns: [\"Store\", \"Payer\"])\n  |> sum()"
    }
   ]
  },
  {
   "title": "Katie Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"grocery\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> drop(columns: [\"Store\"])\n  |> filter(fn: (r) =>  r[\"Payer\"] == \"Katie\")\n  |> sum()"
    }
   ]
  },
  {
   "title": "Carter Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"grocery\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> drop(columns: [\"Store\"])\n  |> filter(fn: (r) =>  r[\"Payer\"] == \"Carter\")\n  |> sum()"
    }
   ]
  },
  {
   "title": "Cumulative Sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 9, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"grocery\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> drop(columns: [\"Store\"])\n  |> sort(columns: [\"_time\"])\n  |> cumulativeSum()"
    }
   ]
  },
  {
   "title": "Costco Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"grocery\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> drop(columns: [\"Payer\"])\n  |> filter(fn: (r) =>  r[\"Store\"] == \"Costco\")\n  |> sum()"
    }
   ]
  },
  {
   "title": "Farm Boy Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"grocery\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> drop(columns: [\"Payer\"])\n  |> filter(fn: (r) =>  r[\"Store\"] == \"Farm Boy\")\n  |> sum()"
    }
   ]
  },
  {
   "title": "Loblaws Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"grocery\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> drop(columns: [\"Payer\"])\n  |> filter(fn: (r) =>  r[\"Store\"] == \"Loblaws\")\n  |> sum()"
    }
   ]
  },
  {
   "title": "Metro Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"grocery\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> drop(columns: [\"Payer\"])\n  |> filter(fn: (r) =>  r[\"Store\"] == \"Metro\")\n  |> sum()"
    }
   ]
  },
  {
   "title": "Others Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"grocery\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>  r[\"Store\"] != \"Loblaws\" and r.Store != \"Costco\" and r.Store != \"Farm Boy\"and r.Store != \"Metro\")\n  |> drop(columns: [\"Payer\", \"Store\"])\n  |> sum()"
    }
   ]
  },
  {
   "title": "Yearly Cumulative Sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 9, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"grocery\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> drop(columns: [\"Store\"])\n  |> sort(columns: [\"_time\"])\n  |> cumulativeSum()"
    }
   ]
  }
 ]
}