{
 "title": "Home Assistant",
 "tags": [
  "home",
  "climate",
  "server"
 ],
 "time": { "from": "now-36h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"home_assistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"°C\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"friendly_name\"] != \"Living Room Climate temperature\")\r\n  |> map(fn: (r) => ({\r\n        _value: r._value, \r\n        _time: r._time, \r\n        name: \"${r[\"friendly_name\"]}\"\r\n    }))\r\n  |> group(columns: [\"name\"])"
    }
   ]
  },
  {
   "title": "Temperature Moving Average",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"home_assistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"°C\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"friendly_name\"] != \"Living Room Climate temperature\")\r\n  |> map(fn: (r) => ({\r\n        _value: r._value, \r\n        _time: r._time, \r\n        name: \"${r[\"friendly_name\"]}\"\r\n    }))\r\n  |> group(columns: [\"name\"])\r\n  // |> movingAverage(n: 20) \r\n  |> timedMovingAverage(every: 30m, period: 3h)\r\n  // |> aggregateWindow(every: 1h, fn: mean)"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "from(bucket: \"home_assistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"%\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> map(fn: (r) => ({\r\n        _value: r._value, \r\n        _time: r._time, \r\n        name: \"${r[\"friendly_name\"]}\"\r\n    }))\r\n  |> group(columns: [\"name\"])"
    }
   ]
  },
  {
   "title": "VOC Index",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "query": "from(bucket: \"home_assistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor.living_room_climate_voc_index\")"
    }
   ]
  },
  {
   "title": "Particulate Matter Levels",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "µg/m³" } },
   "targets": [
    {
     "query": "from(bucket: \"home_assistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"µg/m³\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> timedMovingAverage(every: 10m, period: 20m)\r\n  |> map(fn: (r) => ({\r\n        _value: r._value, \r\n        _time: r._time, \r\n        name: \"${r[\"friendly_name\"]}\"\r\n    }))\r\n  |> group(columns: [\"name\"])"
    }
   ]
  },
  {
   "title": "AC Sensor",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "query": "from(bucket: \"home_assistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"ac_sensor\")\r\n  |> map(fn: (r) => ({\r\n        _value: r._value, \r\n        _time: r._time, \r\n        name: \"${r[\"friendly_name\"]}\"\r\n    }))\r\n  |> sort(columns: [\"_time\"])\r\n  |> group(columns: [\"name\"])\r\n  "
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "query": "from(bucket: \"home_assistant\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> drop(columns: [\"source\"])\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hPa\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> map(fn: (r) => ({\n        _value: r._value, \n        _time: r._time, \n        name: \"${r[\"friendly_name\"]}\"\n    }))\n  |> group(columns: [\"name\"])"
    }
   ]
  }
 ]
}