{
 "title": "Raspberry-Pi",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "linux_host", "query": "DietPi" },
   { "name": "bucket", "query": "rasp-pi" }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"system\")\n  |> filter(fn: (r) => r._field == \"uptime\")\n  |> filter(fn: (r) => r[\"host\"] == \"${linux_host}\")\n  |> last()\n  |> toFloat()\n  |> map(fn: (r) => ({r with _value: r._value / 86400.0}))\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temp\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temp\")\n  |> filter(fn: (r) => r[\"host\"] == \"${linux_host}\")\n  |> last()\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "GPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temperature_gpu\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> last()\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "nCPUs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"system\")\n  |> filter(fn: (r) => r._field == \"n_cpus\")\n  |> filter(fn: (r) => r[\"host\"] == \"${linux_host}\")\n  |> last()\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r._measurement == \"system\")\n  |> filter(fn: (r) => r._field == \"load1\")\n  |> filter(fn: (r) => r[\"host\"] == \"${linux_host}\")\n  |> last()\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"mem\")\n  |> filter(fn: (r) => r._field == \"total\")\n  |> filter(fn: (r) => r[\"host\"] == \"${linux_host}\")\n  |> last()\n  |> map(fn: (r) => ({r with _value: float(v: r._value) / 1024.0 / 1024.0 / 1024.0}))\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"mem\")\n  |> filter(fn: (r) => r._field == \"used_percent\")\n  |> filter(fn: (r) => r[\"host\"] == \"${linux_host}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 3 },
   "targets": [
    {
     "query": "from(bucket: \"rasp-pi\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"DietPi\")\n  |> filter(fn: (r) => r._measurement == \"disk\")\n  |> filter(fn: (r) => r._field == \"used_percent\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 3 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"${linux_host}\")\n  |> filter(fn: (r) => r._field == \"usage_user\" or r._field == \"usage_system\" or r._field == \"usage_idle\")\n  |> filter(fn: (r) => r.cpu == \"cpu-total\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 3 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"system\")\n  |> filter(fn: (r) => r[\"host\"] == \"${linux_host}\")\n  |> filter(fn: (r) => r._field == \"load1\" or r._field == \"load5\" or r._field == \"load15\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"diskio\")\n  |> filter(fn: (r) => r._field == \"read_bytes\" or r._field == \"write_bytes\")\n  |> filter(fn: (r) => r[\"host\"] == \"${linux_host}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> derivative(unit: 1s, nonNegative: false)\n  |> yield(name: \"derivative\")"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"net\")\n  |> filter(fn: (r) => r._field == \"bytes_recv\" or r._field == \"bytes_sent\")\n  |> filter(fn: (r) => r[\"host\"] == \"${linux_host}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> derivative(unit: 1s, nonNegative: false)\n  |> yield(name: \"derivative\")"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"${linux_host}\")\n  |> filter(fn: (r) => r._measurement == \"processes\")\n  |> filter(fn: (r) => r._field == \"running\" or r._field == \"blocked\" or r._field == \"idle\" or r._field == \"unknown\")\n  |> aggregateWindow(every: v.windowPeriod, fn: max)\n  |> yield(name: \"max\")"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"swap\")\n  |> filter(fn: (r) => r._field == \"total\" or r._field == \"used\")\n  |> filter(fn: (r) => r[\"host\"] == \"${linux_host}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temp\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temp\")\n  |> filter(fn: (r) => r[\"host\"] == \"${linux_host}\")\n  |> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  }
 ]
}