apiVersion: traefik.containo.us/v1alpha1
kind: TLSStore
metadata:
  name: default

spec:
  defaultCertificate:
    secretName: default-cloudflare-tls
    # secrets are only available from the namespace that they're defined in