apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-traefik
  namespace: argocd
spec:
  project: default
  source:
    chart: traefik
    repoURL: https://traefik.github.io/charts
    # targetRevision: 21.1.1 # Comment for head
    helm:
      releaseName: traefik
      valueFiles:
        - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: traefik
  syncPolicy:
    syncOptions:
      - CreateNamsepace=true
