apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: default-headers
  namespace: default
spec:
  headers:
    browserXssFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 15552000
    customFrameOptionsValue: SAMEORIGIN
    customRequestHeaders:
      X-Forwarded-Proto: https
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: authelia-basic
  namespace: default
spec:
  forwardAuth:
    address: http://192.168.1.101:9091/api/verify?auth=basic # replace auth with your authelia container name
    trustForwardHeader: true
    authResponseHeaders:
      - Remote-User
      - Remote-Groups
      - Remote-Name
      - Remote-Email
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: authelia-2fa
  namespace: default
spec:
  forwardAuth:
    address: http://192.168.1.101:9091/api/verify?rd=https://auth.juicewizerd.com
    trustForwardHeader: true
    authResponseHeaders:
      - Remote-User
      - Remote-Groups
      - Remote-Name
      - Remote-Email
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: kobo-sync-headers
  namespace: default
spec:
  headers:
    customRequestHeaders:
      X-Scheme: https
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: security-headers
  namespace: default
spec:
  headers:
    customResponseHeaders:
      X-Forwarded-Proto: "https"
      X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex"
      server: ""
    sslProxyHeaders:
      X-Forwarded-Proto: https
    referrerPolicy: "same-origin"
    hostsProxyHeaders:
      - "X-Forwarded-Host"
    customRequestHeaders:
      X-Forwarded-Proto: "https"
    # customResponseHeaders:
    #   X-Forwarded-Proto: "https"
    contentTypeNosniff: true
    browserXssFilter: true
    forceSTSHeader: true
    stsIncludeSubdomains: true
    stsSeconds: 63072000
    stsPreload: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: cloudflare-allowlist
  namespace: default
spec:
  ipWhiteList: # Change to IPAllowList in v3
    sourceRange:
      - 173.245.48.0/20
      - 103.21.244.0/22
      - 103.22.200.0/22
      - 103.31.4.0/22
      - 141.101.64.0/18
      - 108.162.192.0/18
      - 190.93.240.0/20
      - 188.114.96.0/20
      - 197.234.240.0/22
      - 198.41.128.0/17
      - 162.158.0.0/15
      - 104.16.0.0/13
      - 104.24.0.0/14
      - 172.64.0.0/13
      - 131.0.72.0/22
      - 2400:cb00::/32
      - 2606:4700::/32
      - 2803:f800::/32
      - 2405:b500::/32
      - 2405:8100::/32
      - 2a06:98c0::/29
      - 2c0f:f248::/32
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: cors-headers
  namespace: default
spec:
  headers:
    accessControlAllowMethods:
      - GET
      - OPTIONS
      - PUT
    accessControlAllowOriginList:
      - https://homer.juicewizerd.com/
      - https://auth.juicewizerd.com/
      - http://192.168.1.101:9020
    accessControlAllowHeaders: ["x-api-key, Origin, Authorization"]
    accessControlAllowCredentials: true
    accessControlMaxAge: 100
    addVaryHeader: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: crowdsec-bouncer
  namespace: default
spec:
  forwardAuth:
    address: http://192.168.1.101:8080/api/v1/forwardAuth
    trustForwardHeader: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: floc-block
  namespace: default
spec:
  headers:
    customResponseHeaders:
      Permissions-Policy: interest-cohort=()
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: test-compress
  namespace: default
spec:
  compress: {}