---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ntfy-gatus-ep
  namespace: default
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: ntfy
        group: External
        url: https://ntfy.juicewizerd.com/v1/health
        client:
          dns-resolver: tcp://1.1.1.1:53
        conditions:
          - "[STATUS] == 200"
          - "[BODY].healthy == true"
        alerts:
          - type: pushover
