---
apiVersion: traefik.io/v1alpha1
kind: Ingress
metadata:
  name: ntfy-ingress
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: default-crowdsec@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - &host ntfy.juicewizerd.com
      secretName: juicewizerd-le-com-tls
  rules:
    - host: *host
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: ntfy-svc
                port:
                  number: 80
