---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ntfy
spec:
  selector:
    matchLabels:
      app: ntfy
  endpoints:
    - port: ntfy-metrics
      path: /
      interval: 10s
