---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ntfy-ingress
  labels:
    app: ntfy-pod
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`ntfy.juicewizerd.com`)
      kind: Rule
      services:
        - name: ntfy-svc
          port: 80
      middlewares:
        - name: default-headers
        - name: crowdsec
  tls:
    secretName: juicewizerd-le-com-tls
