---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prowlarr-gatus-ep
  namespace: default
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: Prowlarr
        group: Media Server
        url: http://prowlarr.default/ping
        interval: 2m
        conditions:
          - "[STATUS] == 200"
          - "[BODY].status == OK"
