---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.245
spec:
  type: LoadBalancer
  selector:
    app: prowlarr
  ports:
    - name: http-prowlarr-out
      protocol: TCP
      port: 80
      targetPort: http-prowlarr
