apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: prowlarr
spec:
  resyncInterval: 60
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: service-token
        secretNamespace: default
      secretsScope:
        envSlug: dev
        secretsPath: "/prowlarr"
  managedKubeSecretReferences:
    - secretName: prowlarr
      secretNamespace: default
