---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  labels:
    app: prowlarr
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      containers:
        - name: prowlarr
          image: ghcr.io/onedr0p/prowlarr:rolling@sha256:7645fa4904027d22b70ce73bfe86b4a03f604867d717aee4e92da4a950af830e
          env:
            - name: TZ
              value: America/Toronto
          envFrom: &envFrom
            - secretRef:
                name: prowlarr
          ports:
            - containerPort: 9696
              name: http-prowlarr
          livenessProbe: &probe
            httpGet:
              path: /ping
              port: http-prowlarr
            initialDelaySeconds: 10
            failureThreshold: 3
            periodSeconds: 60
            timeoutSeconds: 5
          readinessProbe: *probe
          resources:
            limits:
              memory: 500Mi
              cpu: 1000m
          volumeMounts:
            - mountPath: /config
              name: config-volume
      initContainers:
        - name: init-db
          image: ghcr.io/onedr0p/postgres-init:16.2
          envFrom: *envFrom
      volumes:
        - name: config-volume
          persistentVolumeClaim:
            claimName: prowlarr-pvc
