apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: prowlarr
spec:
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: k3s-f6-lw
        envSlug: dev
        secretsPath: "/prowlarr"
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: default
  managedSecretReference:
    secretName: prowlarr
    secretNamespace: default
