---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: "Carter's Dashboard"
subtitle: "Homer"
logo: "logo.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: false

defaults:
  colorTheme: auto

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link-hover: "#363636"
  dark:
    highlight-primary: "#2E3440"
    highlight-secondary: "#4C566A"
    highlight-hover: "#81A1C1"
    background: "#3B4252"
    card-background: "#2E3440"
    text: "#D8DEE9"
    text-header: "#D8DEE9"
    text-title: "#81A1C1"
    text-subtitle: "#81A1C1"
    card-shadow: rgba(0, 0, 0, 0.4)
    link-hover: "#BF616A"
    # colors from Nord theme: https://github.com/arcticicestudio/nord

# Optional navbar
# links: [] # Allows for navbar without any links
links:
  - name: "Contribute"
    icon: "fab fa-github"
    url: "https://github.com/"
    target: "_blank"
  - name: "Wiki"
    icon: "fas fa-book"
    url: "https://www.wikipedia.org/"
  #   this will link to a second homer page that will load config from
  #   additional-page.yml and keep default config values as in config.yml file
  #   see url field and assets/additional-page.yml.dist used in this example:
  # - name: "another page!"
  #   icon: "fas fa-file-alt"
  #   url: "#additional-page"

# Services
services:
  - name: "Apps"
    icon: "fas fa-film"
    items:
      - name: "Home Assistant"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/home-assistant.svg"
        subtitle: "Smart Home Management"
        tag: "home"
        url: "http://homeassistant.local:8123/"
        target: "_blank"
      - name: "Jellyfin"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/jellyfin.svg"
        subtitle: "Media Center"
        tag: "video"
        url: "http://192.168.1.92:8096/"
        target: "_blank"
        type: "Emby"
        apikey: "096955377f17481fbfebba9e6a501732"
        libraryType: "series"
      - name: "Miniflux"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/miniflux.svg"
        subtitle: "RSS Reader"
        tag: "news"
        url: "https://miniflux.juicewizerd.com/"
        target: "_blank"
      - name: "Calibre-Web"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/calibre-web.svg"
        subtitle: "Ebook Library"
        tag: "app"
        keywords: "books"
        url: "https://books.juicewizerd.com"
        target: "_blank"
      - name: "Kavita"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/kavita.svg"
        subtitle: "Manga Library"
        tag: "app"
        keywords: "books"
        url: "https://kavita.juicewizerd.com"
        target: "_blank"
      - name: "Immich"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/immich.svg"
        subtitle: "Photo backups"
        tag: "app"
        keywords: "photos"
        url: "http://192.168.1.93:2283"
        target: "_blank"

  - name: Starr
    icon: "fas fa-film"
    items:
      - name: "Homarr"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/homarr.svg"
        subtitle: "arr Homepage"
        url: "https://homarr.juicewizerd.com"
        target: "_blank"
      - name: "Jellyseerr"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/jellyseerr.svg"
        tag: "requests"
        subtitle: "Media Requests"
        url: "https://jellyseerr.juicewizerd.com"
        target: "_blank"
      - name: "Radarr"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/radarr.svg"
        tag: "movies"
        subtitle: "Movie Downloader"
        url: "http://192.168.1.93:7878"
        target: "_blank"
        type: "Radarr"
        apikey: "4011babfa3b043df9a824cd986d03f18"
      - name: "Sonarr"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/sonarr.svg"
        tag: "shows"
        subtitle: "TV Downloader"
        url: "http://192.168.1.93:8989"
        target: "_blank"
        type: "Sonarr"
        apikey: "0c8978dcd9474445987a79a520326b80"
      - name: "Prowlarr"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/prowlarr.svg"
        tag: "indexers"
        subtitle: "Index Manager"
        url: "http://192.168.1.245"
        target: "_blank"
        type: "Prowlarr"
        apikey: "e851b6ad7743446d97a49181a01fbaf0"

  - name: "Tools"
    icon: "fas fa-tools"
    items:
      - name: "Uptime-Kuma"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/uptime-kuma.svg"
        # subtitle: "Uptime Checker"
        tag: "uptime"
        url: "https://uptime.juicewizerd.com"
        slug: "home"
        type: "UptimeKuma"
        target: "_blank"
      - name: "ntfy"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/ntfy.svg"
        subtitle: "Notification Server"
        tag: "notify"
        url: "https://ntfy.juicewizerd.com"
        target: "_blank"
      - name: "OpenSpeedTest"
        logo: "https://raw.githubusercontent.com/openspeedtest/Speed-Test/main/assets/images/icons/safari-pinned-tab.svg"
        subtitle: "Local Speed Test"
        tag: "speed-test"
        url: "http://192.168.1.93:3002"
        target: "_blank"
      # - name: "Pi OpenSpeedTest"
      #   logo: "https://raw.githubusercontent.com/openspeedtest/Speed-Test/main/assets/images/icons/safari-pinned-tab.svg"
      #   subtitle: "Local Speed Test"
      #   tag: "speed-test"
      #   url: "http://192.168.1.99:3002"
      #   target: "_blank"
      - name: "ChangeDetection.io"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/changedetection-io.png"
        subtitle: "Change Detection"
        tag: "utility"
        url: "https://change.juicewizerd.com"
        target: "_blank"

  - name: "Network"
    icon: "fa-solid fa-network-wired"
    items:
      - name: "Unifi Network"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/unifi-controller.png"
        tag: "network-controller"
        url: "https://192.168.1.1/network"
        target: "_blank"
      - name: "Unifi Protect"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/unifi-protect.png"
        tag: "NVR"
        url: "https://192.168.1.1/protect"
        target: "_blank"
      - name: "Server AdGuard Home"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/adguard-home.svg"
        subtitle: "DNS-level Ad Blocking"
        tag: "adblocker"
        url: "http://192.168.1.93:8070"
        type: "AdGuardHome"
        target: "_blank"
      - name: "DietPi AdGuard Home"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/adguard-home.svg"
        subtitle: "DNS-level Ad Blocking"
        tag: "adblocker"
        url: "http://192.168.1.86:3010"
        target: "_blank"
      # - name: "Speedtest Tracker"
      #   logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/speedtest-tracker.png"
      #   subtitle: "Scheduled Ookla tests"
      #   tag: "speedtest"
      #   url: "https://192.168.1.93:3003"
      #   target: "_blank"

  - name: "Server"
    icon: "fas fa-server"
    items:
      - name: "Proxmox"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/proxmox.png"
        subtitle: "Virtual Machines"
        tag: "virtual-machines"
        url: "https://192.168.1.98:8006"
        target: "_blank"
      - name: "Grafana"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/grafana.svg"
        subtitle: "Monitoring Dashboards"
        tag: "monitoring"
        # url: "http://192.168.1.93:3000"
        url: "http://graf.juicewizerd.com/d/SH5hMcX7k/home-assistant?orgId=1"
        target: "_blank"
      - name: "Authelia"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/authelia.png"
        subtitle: "SSO Authentication"
        tag: "authentication"
        url: "https://auth.juicewizerd.com"
        target: "_blank"
      - name: "InfluxDB"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/influxdb.svg"
        subtitle: "Time-Series Database"
        tag: "database"
        url: "http://192.168.1.93:8086"
        target: "_blank"

  - name: "Kubernetes"
    icon: "fas fa-server"
    items:
      - name: "ArgoCD"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/argocd.svg"
        subtitle: "GitOps"
        # tag: "virtual-machines"
        url: "https://192.168.1.241"
        target: "_blank"
      - name: "Traefik"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/traefik.svg"
        subtitle: "Kubernetes Proxy Manager"
        tag: "reverse-proxy"
        url: "http://dash.traefik"
        target: "_blank"
      - name: "Longhorn"
        logo: "https://raw.githubusercontent.com/longhorn/website/master/static/img/icon-longhorn.svg"
        subtitle: "Kubernetes Volume Manager"
        tag: "volumes"
        url: "http://longhorn.example.com"
        target: "_blank"
