---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homer-gatus-ep
  namespace: default
  # labels:
  #   gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: Homer
        group: External
        url: http://homer-svc.default/
        interval: 2m
        conditions:
          - "[STATUS] == 200"
        # alerts:
        #   - type: ntfy
