---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - homer-deployment.yaml
  - homer-svc.yaml
  - homer-ingress.yaml
  - gatus.yaml
configMapGenerator:
  - name: homer-config
    files:
      - config.yml
namespace: default
