apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: homarr-ingress
  namespace: default
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`homarr.juicewizerd.com`)
      kind: Rule
      services:
        - name: homarr-svc
          port: 80
      middlewares:
        - name: default-headers
        - name: cors-headers