apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: homebox
  name: homebox-pvc
spec:
  # storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
