apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
  name: default

spec:
  defaultCertificate:
    # secretName: default-cloudflare-tls
    secretName: juicewizerd-le-com-tls
    # secrets are only available from the namespace that they're defined in
