image:
  tag: "v2.10.4"

globalArguments:
  - "--global.sendanonymoususage=false"
  - "--global.checknewversion=false"

additionalArguments:
  - "--serversTransport.insecureSkipVerify=true"
  - "--log.level=INFO"

deployment:
  enabled: true
  kind: DaemonSet

ports:
  web:
    redirectTo: websecure
  websecure:
    http3:
      enabled: true
    tls:
      enabled: true
    middlewares:
      - default-test-compress@kubernetescrd
      - default-floc-block@kubernetescrd
      - default-security-headers@kubernetescrd
      - default-cors-headers@kubernetescrd
      # - default-crowdsec-traefik-bouncer@kubernetescrd

ingressRoute:
  dashboard:
    enabled: false

providers:
  kubernetesCRD:
    enabled: true
    ingressClass: traefik-external
    allowExternalNameServices: true
  kubernetesIngress:
    enabled: true
    allowExternalNameServices: true
    publishedService:
      enabled: false

rbac:
  enabled: true

service:
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.240
  spec:
    # loadBalancerIP: 192.168.1.240 # this should be an IP in the MetalLB range
    externalTrafficPolicy: Local
