---
image:
  tag: "v2.10.4"

deployment:
  enabled: true
  kind: DaemonSet

ingressRoute:
  dashboard:
    enabled: false

providers:
  kubernetesCRD:
    ingressClass: traefik-external
    allowExternalNameServices: true
  kubernetesIngress:
    allowExternalNameServices: true

kubernetesIngress:
  allowExternalNameServices: true

metrics:
  service:
    enabled: true
    disableAPICheck: true

globalArguments:
  - "--global.sendanonymoususage=false"
  - "--global.checknewversion=false"

additionalArguments:
  - "--serversTransport.insecureSkipVerify=true"

ports:
  web:
    redirectTo: websecure
  websecure:
    http3:
      enabled: true
    tls:
      enabled: true
    middlewares:
      - default-test-compress@kubernetescrd
      - default-floc-block@kubernetescrd
      - default-security-headers@kubernetescrd
      - default-cors-headers@kubernetescrd
  metrics:
    expose: true

service:
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.240
  spec:
    externalTrafficPolicy: Local

requests:
  cpu: "100m"
  memory: "50Mi"
limits:
  cpu: "300m"
  memory: "150Mi"
