---
deployment:
  enabled: true
  kind: DaemonSet

providers:
  kubernetesCRD:
    ingressClass: traefik-external
    allowExternalNameServices: true
  kubernetesIngress:
    allowExternalNameServices: true

globalArguments:
  - "--global.sendanonymoususage=false"
  - "--global.checknewversion=false"

additionalArguments:
  - "--serversTransport.insecureSkipVerify=true"
  - "--providers.kubernetesingress.ingressendpoint.publishedservice=traefik/traefik"

ports:
  web:
    redirections:
      entryPoint:
        to: websecure
        scheme: https
        permanent: true
  websecure:
    http3:
      enabled: true
    middlewares:
      - default-test-compress@kubernetescrd
      - default-floc-block@kubernetescrd
      - default-security-headers@kubernetescrd
      - default-cors-headers@kubernetescrd

service:
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.240
  spec:
    externalTrafficPolicy: Local

requests:
  cpu: "100m"
  memory: "50Mi"
limits:
  cpu: "300m"
  memory: "150Mi"
