---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: 6.0.6
      helm:
        valueFiles:
          - $myRepo/bootstrap/argocd/values.yaml
    - repoURL: https://github.com/carterjgreen/home-server.git
      ref: myRepo
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
