---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://github.com/carterjgreen/home-server.git"
    path: manifests/metallb
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
    ignoreDifferences:
      - group: "apiextensions.k8s.io"
        kind: CustomResourceDefinition
        name: bgppeers.metallb.io
        jsonPointers:
          - /spec/conversion/webhook/clientConfig/caBundle
      - group: "apiextensions.k8s.io"
        kind: CustomResourceDefinition
        name: addresspools.metallb.io
        jsonPointers:
          - /spec/conversion/webhook/clientConfig/caBundle
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
