apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-upgrade-controller
  namespace: argocd
spec:
  destination:
    namespace: system-upgrade
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://github.com/rancher/system-upgrade-controller.git
      path: manifests
      targetRevision: v0.14.2
    - repoURL: https://github.com/carterjgreen/home-server.git
      path: manifests/system-upgrade-controller
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
