---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-middlewares
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/carterjgreen/home-server.git
      path: manifests/traefik
  destination:
    server: "https://kubernetes.default.svc"
    namespace: traefik
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
