---
resources:
  limits:
    cpu: 250m
    memory: 750m
  requests:
    cpu: 100m
    memory: 128Mi

persistence:
  enabled: true
  size: 1Gi

admin:
  existingSecret: "grafana"

envFromSecret: ""

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: Prometheus
        url: http://192.168.1.93:9090
      - name: InfluxDB
        type: InfluxDB
        url: http://192.168.1.93:8086
        jsonData:
          version: Flux
          organization: my-org
          default-bucket: home_assistant
          tlsSkipVerify: true
        secureJsonData:
          token: $influx_token

grafana.ini:
  server:
    domain: graf.juicewizerd.com
    enable_gzip: true
  users:
    allow_sign_up: false
    auto_assign_org: true
    auto_assign_role: Viewer
  auth.anonymous:
    enabled: true
  auth.proxy:
    enabled: true
    header_name: Remote-User
    header_property: username
    auto_sign_up: true
    headers: Groups:Remote-Group
    enable_login_token: false
  analytics:
    reporting_enabled: false
