---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: "Carter's Dashboard"
subtitle: "Homer"
logo: "logo.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: false

defaults:
  colorTheme: auto

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link-hover: "#363636"
  dark:
    highlight-primary: "#2E3440"
    highlight-secondary: "#4C566A"
    highlight-hover: "#81A1C1"
    background: "#3B4252"
    card-background: "#2E3440"
    text: "#D8DEE9"
    text-header: "#D8DEE9"
    text-title: "#81A1C1"
    text-subtitle: "#81A1C1"
    card-shadow: rgba(0, 0, 0, 0.4)
    link-hover: "#BF616A"  
    # colors from Nord theme: https://github.com/arcticicestudio/nord

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Contribute"
    icon: "fab fa-github"
    url: "https://github.com/"
    target: "_blank"
  - name: "Wiki"
    icon: "fas fa-book"
    url: "https://www.wikipedia.org/"
  # this will link to a second homer page that will load config from additional-page.yml and keep default config values as in config.yml file
  # see url field and assets/additional-page.yml.dist used in this example:
  - name: "another page!"
    icon: "fas fa-file-alt"
    url: "#additional-page" 

# Services
services:
  - name: "Apps"
    icon: "fas fa-film"
    items:
      - name: "Home Assistant"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/home-assistant.svg"
        subtitle: "Smart Home Management"
        tag: "home"
        url: "http://192.168.1.86:8123/"
        target: "_blank"
      - name: "Jellyfin"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/jellyfin.svg"
        subtitle: "Media Center"
        tag: "video"
        url: "http://192.168.1.101:8096/"
        target: "_blank"
        type: "Emby"
        apikey: "b5b789751bb848699aaee1790e31aa47"
        libraryType: "series"
      - name: "Zigbee2MQTT"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/zigbee2mqtt.svg"
        subtitle: "Zigbee Hub"
        tag: "home"
        url: "http://192.168.1.86:8099/"
        target: "_blank"
      - name: "Calibre-Web"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/calibreweb.svg"
        subtitle: "Ebook Library"
        tag: "app"
        keywords: "books"
        url: "http://192.168.1.101:8083"
        target: "_blank"
      - name: "Immich"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/immich.png"
        subtitle: "Photo backups"
        tag: "app"
        keywords: "photos"
        url: "http://192.168.1.100:2283"
        target: "_blank"
        
  - name: Starr
    icon: "fas fa-film"
    items:
      - name: "Homarr"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/homarr.svg"
        subtitle: "arr Homepage"
        url: "https://homarr.juicewizerd.com"
        target: "_blank" 
      - name: "Jellyseerr"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/jellyseerr.svg"
        tag: "requests"
        subtitle: "Media Requests"
        url: "https://jellyseerr.juicewizerd.com"
        target: "_blank" 
      - name: "Radarr"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/radarr.svg"
        tag: "movies"
        subtitle: "Movie Downloader"
        url: "http://192.168.1.101:7878"
        target: "_blank" 
        type: "Radarr"
        apikey: "4011babfa3b043df9a824cd986d03f18"
      - name: "Sonarr"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/sonarr.svg"
        tag: "shows"
        subtitle: "TV Downloader"
        url: "http://192.168.1.101:8889"
        target: "_blank" 
        type: "Sonarr"
        apikey: "0c8978dcd9474445987a79a520326b80"
      - name: "Prowlarr"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/prowlarr.svg"
        tag: "indexers"
        subtitle: "Index Manager"
        url: "http://192.168.1.101:9696"
        target: "_blank" 
        type: "Prowlarr"
        apikey: "e851b6ad7743446d97a49181a01fbaf0"
      
  - name: "Tools"
    icon: "fas fa-tools"
    items:
      - name: "Uptime-Kuma"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/uptime-kuma.svg"
        # subtitle: "Uptime Checker"
        tag: "uptime"
        url: "https://uptime.juicewizerd.com"
        slug: "home"
        type: "UptimeKuma"
        target: "_blank"
      - name: "ntfy"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/ntfy.png"
        subtitle: "Notification Server"
        tag: "notify"
        url: "https://ntfy.juicewizerd.com"
        target: "_blank"
      - name: "OpenSpeedTest"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/openspeedtest.png"
        subtitle: "Local Speed Test"
        tag: "speed-test"
        url: "http://192.168.1.101:3002"
        target: "_blank"
      - name: "Pi OpenSpeedTest"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/openspeedtest.png"
        subtitle: "Local Speed Test"
        tag: "speed-test"
        url: "http://192.168.1.99:3002"
        target: "_blank"
      - name: "ChangeDetection.io"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/changedetection-io.png"
        subtitle: "Change Detection"
        tag: "utility"
        url: "http://192.168.1.99:5001"
        target: "_blank"
      # - name: "Code-Server"
      #   logo: "assets/icons/vscode.png"
      #   subtitle: "Remote VS Code Editor"
      #   tag: "code editor"
      #   url: "https://vscode.example.com/"
      #   target: "_blank"

  - name: "Network"
    icon: "fa-solid fa-network-wired"
    items:
      - name: "Unifi Network"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/unificontroller.png"
        tag: "network-controller"
        url: "https://192.168.1.1/network"
        target: "_blank"
      - name: "Unifi Protect"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/unifi-protect.png"
        tag: "NVR"
        url: "https://192.168.1.1/protect"
        target: "_blank"
      - name: "Server AdGuard Home"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/adguard-home.png"
        subtitle: "DNS-level Ad Blocking"
        tag: "adblocker"
        url: "http://192.168.1.101:8070"
        type: "AdGuardHome"
        target: "_blank"
      - name: "DietPi AdGuard Home"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/adguard-home.png"
        subtitle: "DNS-level Ad Blocking"
        tag: "adblocker"
        url: "http://192.168.1.99:80"
        # type: "AdGuardHome"
        target: "_blank"
      - name: "Speedtest Tracker"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/speedtest-tracker.png"
        subtitle: "Scheduled Ookla tests"
        tag: "speedtest"
        url: "https://192.168.1.101:3003"
        target: "_blank"

  - name: "Server"
    icon: "fas fa-server"
    items:
      - name: "Proxmox"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/proxmox.png"
        subtitle: "Virtual Machines"
        tag: "virtual-machines"
        url: "https://192.168.1.98:8006"
        target: "_blank"
      - name: "Portainer"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/portainer.svg"
        subtitle: "Docker Container Management"
        tag: "docker"
        url: "http://192.168.1.101:9000"
        type: "Portainer"
        apikey: "ptr_TSj7LxeMIapCJf18wzSHQWitkx0LatYVMtTWLl5RyUQ="
        target: "_blank"
      - name: "Grafana"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/grafana.svg"
        subtitle: "Monitoring Dashboards"
        tag: "monitoring"
        # url: "http://192.168.1.101:3000"
        # url: "http://192.168.1.101:3000/d/SH5hMcX7k/home-assistant?orgId=1"
        url: "http://graf.juicewizerd.com/d/SH5hMcX7k/home-assistant?orgId=1"
        target: "_blank"
      - name: "Traefik"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/traefik.svg"
        subtitle: "Proxy Manager"
        tag: "reverse-proxy"
        url: "http://192.168.1.101:8090"
        target: "_blank"     
      - name: "Authelia"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/authelia.png"
        subtitle: "SSO Authentication"
        tag: "authentication"
        url: "https://auth.juicewizerd.com"
        target: "_blank"                

  - name: "Kubernetes"
    icon: "fas fa-server"
    items:
      - name: "Rancher"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/rancher.png"
        subtitle: "Kubernetes Manager"
        tag: "reverse-proxy"
        url: "https://192.168.1.243"
        target: "_blank"  
      - name: "ArgoCD"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/argocd.png"
        subtitle: "GitOps"
        # tag: "virtual-machines"
        url: "https://192.168.1.241"
        target: "_blank"
      - name: "Traefik"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/svg/traefik.svg"
        subtitle: "Kubernetes Proxy Manager"
        tag: "reverse-proxy"
        url: "http://dash.traefik"
        target: "_blank"    
         
      
