apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homer-ingress
  namespace: default
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    # - web
    - websecure
  routes:
    - match: Host(`homer.juicewizerd.com`)
      kind: Rule
      services:
        - name: homer-svc
          port: 80
      middlewares:
        - name: crowdsec-authelia
  tls:
    secretName: juicewizerd-le-com-tls