apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crowdsec
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://crowdsecurity.github.io/helm-charts
      chart: crowdsec
      targetRevision: 0.9.5
      helm:
        valueFiles:
        - $myRepo/crowdsec/crowdsec-values.yaml
    - repoURL: https://github.com/carterjgreen/home-server.git
      ref: myRepo
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
