apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-traefik
  namespace: argocd
spec:
  project: default
  sources:
    # https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/#helm-value-files-from-external-git-repository
    - repoURL: https://traefik.github.io/charts
      chart: traefik
      targetRevision: 21.2.0
      helm:
        releaseName: traefik
        valueFiles:
        - $myRepo/traefik/traefik-values.yaml
    - repoURL: https://github.com/carterjgreen/home-server.git
      ref: myRepo
  destination:
    server: "https://kubernetes.default.svc"
    namespace: traefik
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamsepace=true
