---
apiVersion: v1
kind: ConfigMap
metadata:
  name: change-gatus-ep
  namespace: default
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: LLDAP
        group: Internal
        url: http://192.168.1.243:17170/health
        interval: 2m
        conditions:
          - "[STATUS] == 200"
        alerts:
          - type: pushover
