---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: lldap
  name: lldap-data
  namespace: lldap
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
