---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app: lldap
  name: lldap
  namespace: lldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lldap
  strategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        lldap: https://github.com/nitnelave/lldap
        k8s: https://github.com/Evantage-WS/lldap-kubernetes
      labels:
        app: lldap
    spec:
      containers:
        - env:
            - name: TZ
              value: America/Toronto
          envFrom: &envFrom
            - secretRef:
                name: lldap-credentials
          image: lldap/lldap:v0.5.0
          name: lldap
          ports:
            - containerPort: 3890
            - containerPort: 17170
          livenessProbe:
            httpGet:
              path: /health
              port: 17170
            initialDelaySeconds: 40
            failureThreshold: 3
            periodSeconds: 60
            timeoutSeconds: 10
          volumeMounts:
            - mountPath: /data
              name: lldap-data
      initContainers:
        - name: init-db
          image: ghcr.io/onedr0p/postgres-init:16.3
          envFrom: *envFrom
      restartPolicy: Always
      volumes:
        - name: lldap-data
          persistentVolumeClaim:
            claimName: lldap-data
