apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: lldap
  namespace: lldap
spec:
  resyncInterval: 60
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: service-token
        secretNamespace: default
      secretsScope:
        envSlug: dev
        secretsPath: "/lldap"
  managedKubeSecretReferences:
    secretName: lldap-credentials
    secretNamespace: lldap
