apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: lldap
  namespace: lldap
spec:
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: k3s
        envSlug: dev
        secretsPath: "/lldap"
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: default
  managedSecretReference:
    secretName: lldap-credentials
    secretNamespace: lldap
