---
server:
  log_level: info

metrics:
  global:
    scrape_interval: 1m
  configs:
    - name: agent
      scrape_configs:
        - job_name: "sonarr"
          static_configs:
            - targets: ["sonarr-exporter:9707"]
        - job_name: "radarr"
          static_configs:
            - targets: ["radarr-exporter:9708"]
        - job_name: "prowlarr"
          static_configs:
            - targets: ["prowlarr-exporter:9710"]
        - job_name: "sabnzbd"
          static_configs:
            - targets: ["sabnzbd-exporter:9712"]
        - job_name: "nut"
          metrics_path: /ups_metrics
          scrape_interval: 30s
          static_configs:
            - targets: ["nuts-exporter:9199"]
        - job_name: "unifipoller"
          scrape_interval: 30s
          static_configs:
            - targets: ["unpoller:9130"]
      remote_write:
        - url: http://192.168.1.93:9090/api/v1/write
