---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - agent-deployment.yaml
configMapGenerator:
  - name: agent-config
    files:
      - agent.yaml
namespace: default # select namespace for whole application
