apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: adguard
spec:
  resyncInterval: 60
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: service-token
        secretNamespace: default
      secretsScope:
        envSlug: dev
        secretsPath: "/adguard"
  managedKubeSecretReferences:
    - secretName: adguard
      secretNamespace: default
