---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: adguardhome-sync
  labels:
    app: adguardhome-sync
spec:
  schedule: "*/10 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: sync
              image: ghcr.io/bakito/adguardhome-sync:v0.4.14
              env:
                - name: TZ
                  value: America/Toronto
                - name: API_PORT
                  value: "0"
                - name: CRON
                  value: ""
                - name: RUNONSTART
                  value: "true"
              envFrom:
                - secretRef:
                    name: adguard
              resources:
                limits:
                  memory: 100Mi
                  cpu: 100m
          restartPolicy: OnFailure
