---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: changedetection
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://github.com/carterjgreen/home-server.git"
    path: manifests/changedetection
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
