---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: change
  name: change-pvc
spec:
  # storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
