---
apiVersion: v1
kind: ConfigMap
metadata:
  name: change-gatus-ep
  namespace: default
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: changedetection.io
        group: external
        url: https://change.juicewizerd.com
        client:
          dns-resolver: tcp://1.1.1.1:53
        conditions:
          - "[STATUS] == 200"
        alerts:
          - type: pushover
