# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/cluster_v1.json
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: database
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16.1-18
  primaryUpdateStrategy: unsupervised
  storage:
    size: 10Gi
    storageClass: local-path
  superuserSecret:
    name: cnpg-secret
  bootstrap:
    recovery:
      source: b2backup
  postgresql:
    parameters:
      max_connections: "600"
      shared_buffers: 512MB
  monitoring:
    enablePodMonitor: true
  backup:
    retentionPolicy: 14d
    barmanObjectStore: &objectStore
      wal:
        compression: bzip2
        maxParallel: 4
      destinationPath: s3://carter-cnpg/
      endpointURL: https://s3.us-west-004.backblazeb2.com
      serverName: cnpg-1
      s3Credentials:
        accessKeyId:
          name: cnpg-secret
          key: aws-access-key-id
        secretAccessKey:
          name: cnpg-secret
          key: aws-secret-access-key
  externalClusters:
    - name: b2backup
      barmanObjectStore: *objectStore
