---
## Repository: authelia https://charts.authelia.com
## Chart: authelia

domain: juicewizerd.com

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik-external
  tls:
    secret: juicewizerd-le-com-tls
  traefikCRD:
    enabled: true
    entryPoints:
      - websecure

pod:
  kind: DaemonSet
  env:
    - name: TZ
      value: America/Toronto
  resources:
    limits:
      cpu: "4.00"
      memory: 125Mi
    requests:
      cpu: "0.25"
      memory: 50Mi

secret:
  existingSecret: authelia

configMap:
  enabled: true
  key: configuration.yaml
  server:
    host: 0.0.0.0
    buffers:
      read: 10485760 # Large for calibre web
      write: 8192
    timeouts:
      read: 6s
      write: 6s
  telemtry:
    enabled: true
    serviceMonitor:
      enabled: true
  default_redirection_url: https://auth.juicewizerd.com
  theme: auto
  totp:
    issuer: juicewizerd.com
  authentication_backend:
    password_reset:
      disable: false
    refresh_interval: 1m
    ldap:
      implementation: custom
      url: ldap://lldap-service.lldap.svc.cluster.local:3890
      timeout: 5s
      start_tls: false
      base_dn: dc=juicewizerd,dc=com
      username_attribute: uid
      additional_users_dn: ou=people
      users_filter: "(&(|({username_attribute}={input})({mail_attribute}={input}))(objectClass=person))"
      additional_groups_dn: ou=groups
      groups_filter: "(member={dn})"
      group_name_attribute: cn
      mail_attribute: mail
      display_name_attribute: displayName
      user: uid=admin,ou=people,dc=juicewizerd,dc=com
  identity_providers:
    oidc:
      enabled: true
      cors:
        endpoints: ["authorization", "token", "revocation", "introspection"]
        allowed_origins_from_client_redirect_uris: true
      clients:
        - id: grafana
          description: Grafana
          secret: "$argon2id$v=19$m=65536,t=3,p=4$FLt03HU9Jc8771XThBjsxA$Jqb+Op0qM+FzuMZHnfvARqElHeW6Rr07XS5Z0KUu6W4"
          redirect_uris: ["https://graf.juicewizerd.com/login/generic_oauth"]

  access_control:
    default_policy: two_factor
    rules:
      - domain: # Already hass 2FA
          - "hass.juicewizerd.com"
        policy: bypass
      # Kobo bypass
      - domain: "books.juicewizerd.com"
        policy: bypass
        resources:
          - "^/kobo([/?].*)?$"
      # Home assistant app bypass
      - domain:
          - "hass.juicewizerd.com"
        policy: bypass
        resources:
          - "^/api([/?].*)?$"
          - "^/auth/token.*"
          - "^/.external_auth=.*"
          - "^/service_worker.js"
          - "^/static.*"
          - "^/local.*"
          - "^/hacsfiles.*"
          - "^/frontend_latest.*"

  session:
    name: authelia_session
    domain: juicewizerd.com
    expiration: 1h
    inactivity: 2h
    redis:
      host: 192.168.1.91

  storage:
    postgres:
      host: 192.168.1.91
      port: 5433

  notifier:
    filesystem:
      enabled: true
    smtp:
      enabled: false
