---
# yaml-language-server: $schema=https://raw.githubusercontent.com/authelia/chartrepo/refs/heads/master/charts/authelia/values.schema.json
annotations:
  reloader.stakater.com/auto: "true"
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik-external
  tls:
    secret: juicewizerd-le-com-tls
  traefikCRD:
    enabled: true
    entryPoints:
      - websecure
pod:
  kind: DaemonSet
  env:
    - name: TZ
      value: America/Toronto
  resources:
    limits:
      cpu: "4.00"
      memory: 125Mi
    requests:
      cpu: "0.25"
      memory: 50Mi
secret:
  existingSecret: authelia
  additionalSecrets:
    authelia:
      items:
        - key: "oidc.jwk.RS256.pem"
configMap:
  server:
    buffers:
      read: 10485760 # Large for calibre web
      write: 8192
  log:
    format: json
  telemetry:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  theme: auto
  totp:
    issuer: &domain juicewizerd.com
  authentication_backend:
    ldap:
      enabled: true
      implementation: custom
      address: ldap://lldap-service.lldap.svc.cluster.local:3890
      timeout: 5s
      start_tls: false
      base_dn: dc=juicewizerd,dc=com
      additional_users_dn: ou=people
      users_filter: "(&(|({username_attribute}={input})({mail_attribute}={input}))(objectClass=person))"
      additional_groups_dn: ou=groups
      groups_filter: "(member={dn})"
      attributes:
        username: uid
        group_name: cn
        mail: mail
        display_name: displayName
      user: uid=admin,ou=people,dc=juicewizerd,dc=com
  access_control:
    default_policy: two_factor
    rules:
      - domain: # Already hass 2FA
          - "hass.juicewizerd.com"
        policy: bypass
      # Kobo bypass
      - domain: "books.juicewizerd.com"
        policy: bypass
        resources:
          - "^/kobo([/?].*)?$"
      # Home assistant app bypass
      - domain:
          - "hass.juicewizerd.com"
        policy: bypass
        resources:
          - "^/api([/?].*)?$"
          - "^/auth/token.*"
          - "^/.external_auth=.*"
          - "^/service_worker.js"
          - "^/static.*"
          - "^/local.*"
          - "^/hacsfiles.*"
          - "^/frontend_latest.*"
  session:
    redis:
      enabled: true
      host: redis-headless.database.svc.cluster.local
    cookies:
      - domain: *domain
        subdomain: auth
  storage:
    postgres:
      enabled: true
      address: postgres-rw.database.svc.cluster.local
  notifier:
    smtp:
      enabled: true
      address: smtp://smtp.gmail.com:587
      timeout: 20s
      username: juicewizerd@gmail.com
      sender: juicewizerd@gmail.com
      identifier: *domain
  identity_providers:
    oidc:
      enabled: true
      jwks:
        - key:
            path: "/secrets/authelia/oidc.jwk.RS256.pem"
      cors:
        endpoints: ["authorization", "token", "revocation", "introspection"]
        allowed_origins_from_client_redirect_uris: true
      clients:
        - client_id: grafana
          description: Grafana
          client_secret: "$argon2id$v=19$m=65536,t=3,p=4$FLt03HU9Jc8771XThBjsxA$Jqb+Op0qM+FzuMZHnfvARqElHeW6Rr07XS5Z0KUu6W4"
          public: false
          authorization_policy: "two_factor"
          require_pkce: true
          pkce_challenge_method: "S256"
          redirect_uris:
            - "https://graf.juicewizerd.com/login/generic_oauth"
          scopes:
            - openid
            - profile
            - groups
            - email
          userinfo_signed_response_alg: "none"
          token_endpoint_auth_method: "client_secret_basic"
          allow_multiple_auth_methods: true
