---
apiVersion: v1
kind: Service
metadata:
  name: radarr
spec:
  type: LoadBalancer
  selector:
    app: radarr
  ports:
    - name: http-radarr-out
      protocol: TCP
      port: 80
      targetPort: http-radarr
