apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: juicewizerd-le-com
  namespace: default
spec:
  secretName: juicewizerd-le-com-tls
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
  commonName: "*.juicewizerd.com"
  dnsNames:
  - "juicewizerd.com"
  - "*.juicewizerd.com"
