---
apiVersion: v1
kind: ConfigMap
metadata:
  name: radarr-gatus-ep
  namespace: default
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: radarr
        group: Media Server
        url: http://radarr.default/ping
        interval: 2m
        conditions:
          - "[STATUS] == 200"
          - "[BODY].status == OK"
        alerts:
          - type: ntfy
