apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: radarr
spec:
  resyncInterval: 60
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: service-token
        secretNamespace: default
      secretsScope:
        envSlug: dev
        secretsPath: "/radarr"
  managedKubeSecretReferences:
    - secretName: radarr
      secretNamespace: default
