---
name: Yaml Lint
on: # yamllint disable-line rule:truthy
  - push
jobs:
  lint-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
