container_runtime: containerd
image:
  tag: "v1.4.6"
agent:
  acquisition:
    - namespace: traefik
      podName: traefik-*
      program: traefik
    - namespace: default
      podName: authelia-*
      program: authelia
  env:
    - name: COLLECTIONS
      value: "crowdsecurity/traefik LePresidente/authelia crowdsecurity/home-assistant"
    - name: TZ
      value: "America/Toronto"
lapi:
  env:
    - name: ENROLL_KEY
      valueFrom:
        secretKeyRef:
          name: crowdsec
          key: ENROLL_KEY
    - name: ENROLL_INSTANCE_NAME
      value: "k3s_cluster"
  persistentVolume:
    # -- Persistent volume for data folder. Stores e.g. registered bouncer api keys
    data:
      enabled: true
      accessModes:
        - ReadWriteOnce
      storageClassName: "longhorn"
      size: 1Gi
    # -- Persistent volume for config folder. Stores e.g. online api credentials
    config:
      enabled: true
      accessModes:
        - ReadWriteOnce
      storageClassName: "longhorn"
      size: 100Mi