apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: bidgely
spec:
  resyncInterval: 60
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: service-token
        secretNamespace: default
      secretsScope:
        envSlug: dev
        secretsPath: "/bidgely"
  managedSecretReference:
    secretName: bidgely
    secretNamespace: default
